# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-langeuropean
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live langeuropean collection — Other European languages
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/25/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live langeuropean collection (Other European languages) — the texmf-dist data tree
from tlnet snapshot 20260925, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
armtex
babel-albanian
babel-bosnian
babel-breton
babel-croatian
babel-danish
babel-dutch
babel-estonian
babel-finnish
babel-friulan
babel-hungarian
babel-icelandic
babel-irish
babel-kurmanji
babel-latin
babel-latvian
babel-lithuanian
babel-macedonian
babel-norsk
babel-occitan
babel-piedmontese
babel-romanian
babel-romansh
babel-samin
babel-scottish
babel-slovenian
babel-swedish
babel-turkish
babel-welsh
finbib
hrlatex
huaz
hulipsum
hyphen-albanian
hyphen-croatian
hyphen-danish
hyphen-dutch
hyphen-estonian
hyphen-finnish
hyphen-friulan
hyphen-hungarian
hyphen-icelandic
hyphen-irish
hyphen-kurmanji
hyphen-latin
hyphen-latvian
hyphen-lithuanian
hyphen-macedonian
hyphen-norwegian
hyphen-occitan
hyphen-piedmontese
hyphen-romanian
hyphen-romansh
hyphen-slovenian
hyphen-swedish
hyphen-turkish
hyphen-uppersorbian
hyphen-welsh
lithuanian
nevelok
rojud
swebib
turkce-sayi
turkmen
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/bibtex/bst/finbib/finplain.bst
%{_tl_texmf}/bibtex/bst/swebib/sweabbrv.bst
%{_tl_texmf}/bibtex/bst/swebib/swealpha.bst
%{_tl_texmf}/bibtex/bst/swebib/sweplain.bst
%{_tl_texmf}/bibtex/bst/swebib/sweplnat.bst
%{_tl_texmf}/bibtex/bst/swebib/sweunsrt.bst
%{_tl_texmf}/fonts/afm/public/armenian/arssb10.afm
%{_tl_texmf}/fonts/afm/public/armenian/arssbs10.afm
%{_tl_texmf}/fonts/afm/public/armenian/arssr10.afm
%{_tl_texmf}/fonts/afm/public/armenian/arsssl10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmb10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmbi10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmbs10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmi10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmr10.afm
%{_tl_texmf}/fonts/afm/public/armenian/artmsl10.afm
%{_tl_texmf}/fonts/enc/dvips/lithuanian/latin7x.enc
%{_tl_texmf}/fonts/map/dvips/armenian/arss.map
%{_tl_texmf}/fonts/map/dvips/armenian/artm.map
%{_tl_texmf}/fonts/map/dvips/lithuanian/l7x-urwvn.map
%{_tl_texmf}/fonts/map/dvips/rojud/rojud.map
%{_tl_texmf}/fonts/source/public/armenian/arssb10.mf
%{_tl_texmf}/fonts/source/public/armenian/arssbs10.mf
%{_tl_texmf}/fonts/source/public/armenian/arssr10.mf
%{_tl_texmf}/fonts/source/public/armenian/arsssl10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmb10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmbi10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmbs10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmi10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmr10.mf
%{_tl_texmf}/fonts/source/public/armenian/artmsl10.mf
%{_tl_texmf}/fonts/source/public/armenian/ps2mfbas.mf
%{_tl_texmf}/fonts/tfm/public/armenian/arssb10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/arssbs10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/arssr10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/arsssl10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmb10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmbi10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmbs10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmi10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmr10.tfm
%{_tl_texmf}/fonts/tfm/public/armenian/artmsl10.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uagd.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uagdo.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uagk.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uagko.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ubkd.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ubkdi.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ubkl.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ubkli.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ucrb.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ucrbo.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ucrr.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-ucrro.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvb.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvbc.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvbo.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvboc.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvr.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvrc.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvro.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uhvroc.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uncb.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uncbi.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uncr.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uncri.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uplb.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uplbi.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uplr.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uplri.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-utmb.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-utmbi.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-utmr.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-utmri.tfm
%{_tl_texmf}/fonts/tfm/public/lithuanian/l7x-uzcmi.tfm
%{_tl_texmf}/fonts/tfm/public/rojud/rojud.tfm
%{_tl_texmf}/fonts/type1/public/armenian/arssb10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/arssb10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/arssbs10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/arssbs10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/arssr10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/arssr10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/arsssl10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/arsssl10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmb10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmb10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmbi10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmbi10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmbs10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmbs10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmi10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmi10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmr10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmr10.pfm
%{_tl_texmf}/fonts/type1/public/armenian/artmsl10.pfb
%{_tl_texmf}/fonts/type1/public/armenian/artmsl10.pfm
%{_tl_texmf}/fonts/type1/public/rojud/rojud.pfb
%{_tl_texmf}/tex/generic/babel-albanian/albanian.ldf
%{_tl_texmf}/tex/generic/babel-bosnian/bosnian.ldf
%{_tl_texmf}/tex/generic/babel-breton/breton.ldf
%{_tl_texmf}/tex/generic/babel-croatian/croatian.ldf
%{_tl_texmf}/tex/generic/babel-danish/danish.ldf
%{_tl_texmf}/tex/generic/babel-dutch/afrikaans.ldf
%{_tl_texmf}/tex/generic/babel-dutch/dutch.ldf
%{_tl_texmf}/tex/generic/babel-estonian/estonian.ldf
%{_tl_texmf}/tex/generic/babel-finnish/finnish.ldf
%{_tl_texmf}/tex/generic/babel-friulan/friulan.ldf
%{_tl_texmf}/tex/generic/babel-hungarian/magyar.ldf
%{_tl_texmf}/tex/generic/babel-icelandic/icelandic.ldf
%{_tl_texmf}/tex/generic/babel-irish/irish.ldf
%{_tl_texmf}/tex/generic/babel-kurmanji/kurmanji.ldf
%{_tl_texmf}/tex/generic/babel-latin/classicallatin.ldf
%{_tl_texmf}/tex/generic/babel-latin/classiclatin.ldf
%{_tl_texmf}/tex/generic/babel-latin/ecclesiasticallatin.ldf
%{_tl_texmf}/tex/generic/babel-latin/ecclesiasticallatin.lua
%{_tl_texmf}/tex/generic/babel-latin/ecclesiasticlatin.ldf
%{_tl_texmf}/tex/generic/babel-latin/latin.ldf
%{_tl_texmf}/tex/generic/babel-latin/medievallatin.ldf
%{_tl_texmf}/tex/generic/babel-latvian/latvian.ldf
%{_tl_texmf}/tex/generic/babel-lithuanian/lithuanian.ldf
%{_tl_texmf}/tex/generic/babel-macedonian/macedonian.ldf
%{_tl_texmf}/tex/generic/babel-norsk/norsk.ldf
%{_tl_texmf}/tex/generic/babel-norsk/norwegian.ldf
%{_tl_texmf}/tex/generic/babel-norsk/nynorsk.ldf
%{_tl_texmf}/tex/generic/babel-occitan/occitan.ldf
%{_tl_texmf}/tex/generic/babel-piedmontese/piedmontese.ldf
%{_tl_texmf}/tex/generic/babel-romanian/romanian.ldf
%{_tl_texmf}/tex/generic/babel-romansh/romansh.ldf
%{_tl_texmf}/tex/generic/babel-samin/northernsami.ldf
%{_tl_texmf}/tex/generic/babel-samin/samin.ldf
%{_tl_texmf}/tex/generic/babel-scottish/scottish.ldf
%{_tl_texmf}/tex/generic/babel-scottish/scottishgaelic.ldf
%{_tl_texmf}/tex/generic/babel-slovenian/slovene.ldf
%{_tl_texmf}/tex/generic/babel-slovenian/slovenian.ldf
%{_tl_texmf}/tex/generic/babel-swedish/swedish.ldf
%{_tl_texmf}/tex/generic/babel-turkish/turkish.ldf
%{_tl_texmf}/tex/generic/babel-welsh/welsh.ldf
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-cy.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-da.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-et.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-fi-x-school.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-fi.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-fur.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-ga.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-hr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-hsb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-hu.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-is.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-kmr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-la-x-classic.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-la-x-liturgic.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-la.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-lt.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-lv.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-mk.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-nb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-nl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-nn.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-oc.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-pms.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-rm.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-ro.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-sl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-sq.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-sv.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-tr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-cy.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-da.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-et.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-fi-x-school.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-fi.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-fur.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-ga.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-hr.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-hsb.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-hu.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-is.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-kmr.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-la-x-liturgic.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-la.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-lt.l7x.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-lv.l7x.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-nb.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-nl.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-nn.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-oc.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-rm.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-ro.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-sl.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-sq.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-sv.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-tr.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/quote/hyph-quote-fur.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/quote/hyph-quote-oc.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/quote/hyph-quote-pms.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/quote/hyph-quote-sq.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex-8bit/hyph-la-x-classic.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex-8bit/hyph-mk.macedonian.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-cy.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-da.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-et.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-fi-x-school.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-fi.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-fur.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-ga.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-hr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-hsb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-hu.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-is.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-kmr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-la-x-classic.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-la-x-liturgic.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-la.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-lt.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-lv.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-mk.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-nb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-nl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-nn.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-no.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-oc.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-pms.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-rm.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-ro.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-sl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-sq.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-sv.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-tr.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-cy.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-da.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-et.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-fi-x-school.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-fi.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-fur.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-ga.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-ga.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-hr.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-hsb.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-hsb.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-hu.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-is.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-kmr.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-la-x-classic.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-la-x-liturgic.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-la.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-lt.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-lv.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-mk.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nb.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nb.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nl.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nl.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nn.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-nn.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-oc.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-pms.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-rm.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-ro.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-sl.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-sq.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-sv.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-tr.pat.txt
%{_tl_texmf}/tex/latex/armenian/armscii8.def
%{_tl_texmf}/tex/latex/armenian/armtex.sty
%{_tl_texmf}/tex/latex/armenian/ot6cmr.fd
%{_tl_texmf}/tex/latex/armenian/ot6cmss.fd
%{_tl_texmf}/tex/latex/armenian/ot6enc.def
%{_tl_texmf}/tex/latex/armenian/ot6enc.dfu
%{_tl_texmf}/tex/latex/hrlatex/fsbispit.cls
%{_tl_texmf}/tex/latex/hrlatex/fsbmath.sty
%{_tl_texmf}/tex/latex/hrlatex/hrlatex.sty
%{_tl_texmf}/tex/latex/huaz/huaz.sty
%{_tl_texmf}/tex/latex/hulipsum/hulipsum.sty
%{_tl_texmf}/tex/latex/lithuanian/cp775.def
%{_tl_texmf}/tex/latex/lithuanian/l7xenc.def
%{_tl_texmf}/tex/latex/lithuanian/l7xenc.dfu
%{_tl_texmf}/tex/latex/lithuanian/l7xenc.sty
%{_tl_texmf}/tex/latex/lithuanian/l7xuag.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xubk.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xucr.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xuhv.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xunc.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xupl.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xutm.fd
%{_tl_texmf}/tex/latex/lithuanian/l7xuzc.fd
%{_tl_texmf}/tex/latex/lithuanian/latin7.def
%{_tl_texmf}/tex/latex/nevelok/nevelok.sty
%{_tl_texmf}/tex/latex/rojud/ot1rojud.fd
%{_tl_texmf}/tex/latex/rojud/rojud.sty
%{_tl_texmf}/tex/latex/rojud/turojud.fd
%{_tl_texmf}/tex/latex/turkmen/turkmen.ldf
%{_tl_texmf}/tex/lualatex/turkce-sayi/turkce-sayi.lua
%{_tl_texmf}/tex/lualatex/turkce-sayi/turkce-sayi.sty
%{_tl_texmf}/tex/plain/armenian/arm.tex
%{_tl_texmf}/tex/plain/armenian/armkb-a8.tex
%{_tl_texmf}/tex/plain/armenian/armkb-u8.tex

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- rolled to tlnet snapshot 20260925 (64 members)
