# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. The scheme-full catch-all: requires every group at this
# snapshot's version (docs excluded by design; binaries pair from Fedora).
Name:           texlive-meta
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live scheme-full, without documentation
BuildArch:      noarch
License:        GPL+ and others (TeX Live collective licenses)
URL:            https://tug.org/texlive/

Requires:       texlive-basic = %{version}
Requires:       texlive-bibtexextra = %{version}
Requires:       texlive-binextra = %{version}
Requires:       texlive-context = %{version}
Requires:       texlive-fontsextra = %{version}
Requires:       texlive-fontsrecommended = %{version}
Requires:       texlive-fontutils = %{version}
Requires:       texlive-formatsextra = %{version}
Requires:       texlive-games = %{version}
Requires:       texlive-humanities = %{version}
Requires:       texlive-langarabic = %{version}
Requires:       texlive-langchinese = %{version}
Requires:       texlive-langcjk = %{version}
Requires:       texlive-langcyrillic = %{version}
Requires:       texlive-langczechslovak = %{version}
Requires:       texlive-langenglish = %{version}
Requires:       texlive-langeuropean = %{version}
Requires:       texlive-langfrench = %{version}
Requires:       texlive-langgerman = %{version}
Requires:       texlive-langgreek = %{version}
Requires:       texlive-langitalian = %{version}
Requires:       texlive-langjapanese = %{version}
Requires:       texlive-langkorean = %{version}
Requires:       texlive-langother = %{version}
Requires:       texlive-langpolish = %{version}
Requires:       texlive-langportuguese = %{version}
Requires:       texlive-langspanish = %{version}
Requires:       texlive-latex = %{version}
Requires:       texlive-latexextra = %{version}
Requires:       texlive-latexrecommended = %{version}
Requires:       texlive-luatex = %{version}
Requires:       texlive-mathscience = %{version}
Requires:       texlive-metapost = %{version}
Requires:       texlive-music = %{version}
Requires:       texlive-pictures = %{version}
Requires:       texlive-plaingeneric = %{version}
Requires:       texlive-pstricks = %{version}
Requires:       texlive-publishers = %{version}
Requires:       texlive-xetex = %{version}

%description
Metapackage installing every texlive-* group from tlnet snapshot
20260925 — Arch's texlive-meta shape, minus documentation. TeX engines
themselves come from Fedora's texlive packaging.

%build
cat > README <<'EOF'
texlive-meta — TeX Live scheme-full without documentation.

All texlive-* groups installed by this metapackage are pinned to tlnet
snapshot 20260925. Groups roll biweekly; dnf keeps them on one snapshot
via the version-pinned inter-group Requires.
EOF

%files
%doc README

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- metapackage for tlnet snapshot 20260925 (39 groups)
