# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-music
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live music collection — Music packages
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/25/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-latex = %{version}

%description
TeX Live music collection (Music packages) — the texmf-dist data tree
from tlnet snapshot 20260925, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
abc
bagpipe
chordbars
chordbox
ddphonism
figbas
fretplot
gchords
gregoriotex
gtrcrd
guitar
guitarchordschemes
guitartabs
harmony
leadsheets
liederbuch
lilyglyphs
lyluatex
m-tx
mousik
musical
musicography
musixguit
musixtex
musixtex-fonts
musixtnt
octave
piano
pmx
pmxchords
recorder-fingering
songbook
songproj
songs
undar-digitacion
xpiano
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/dvips/musixtex/psslurs.pro
%{_tl_texmf}/fonts/afm/public/figbas/cmrj.afm
%{_tl_texmf}/fonts/afm/public/figbas/cmssj.afm
%{_tl_texmf}/fonts/afm/public/figbas/plrj.afm
%{_tl_texmf}/fonts/map/dvips/figbas/figbas.map
%{_tl_texmf}/fonts/map/dvips/musixtex-fonts/musix.map
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/FONTLOG
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/LICENSE.OFL
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-11.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-13.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-14.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-16.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-18.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-20.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-23.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-26.otf
%{_tl_texmf}/fonts/opentype/public/lilyglyphs/emmentaler-brace.otf
%{_tl_texmf}/fonts/opentype/public/musixtex-fonts/MuseJazzText.otf
%{_tl_texmf}/fonts/source/gregoriotex/convertsfdtottf.py
%{_tl_texmf}/fonts/source/gregoriotex/fonts_README.md
%{_tl_texmf}/fonts/source/gregoriotex/greciliae-base.sfd
%{_tl_texmf}/fonts/source/gregoriotex/greextra.sfd
%{_tl_texmf}/fonts/source/gregoriotex/gregall.sfd
%{_tl_texmf}/fonts/source/gregoriotex/grelaon.sfd
%{_tl_texmf}/fonts/source/gregoriotex/gresgmodern.sfd
%{_tl_texmf}/fonts/source/gregoriotex/simplify.py
%{_tl_texmf}/fonts/source/gregoriotex/squarize.py
%{_tl_texmf}/fonts/source/gregoriotex/stemsschemas.py
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musexgen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix25.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musix29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musixgen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musixsps.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/musixspx.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/mxsk.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadf29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xadfgen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xdrawsl.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xdrawzl.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg25.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreg29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xgreggen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xppff10.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xppffgen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld11d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld13d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld16d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld24d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsld29d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsldd20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xsldu20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslgen.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslgend.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslgenu.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd11d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd13d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd16d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd24d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhd29d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu11d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu13d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu16d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu24d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhu29d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhz-o.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhz.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhz20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslhz20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu11.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu11d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu13.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu13d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu16.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu16d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu24.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu24d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu29.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslu29d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslud20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslup20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslz.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslz20.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xslz20d.mf
%{_tl_texmf}/fonts/source/public/musixtex-fonts/xtie20.mf
%{_tl_texmf}/fonts/tfm/public/figbas/cmrj.tfm
%{_tl_texmf}/fonts/tfm/public/figbas/cmssj.tfm
%{_tl_texmf}/fonts/tfm/public/figbas/plrj.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/MuseJazzText.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/feta20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/frenchtab.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix25.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musix29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musixsps.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/musixspx.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/mxsk.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xadf29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xgreg29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xppff10.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld11d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld13d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld16d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld24d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsld29d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsldd20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xsldu20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd11d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd13d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd16d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd24d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhd29d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu11d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu13d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu16d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu20m.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu24d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhu29d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhz20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslhz20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu11.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu11d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu13.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu13d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu16.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu16d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu24.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu24d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu29.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslu29d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslud20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslup20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslz20.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xslz20d.tfm
%{_tl_texmf}/fonts/tfm/public/musixtex-fonts/xtie20.tfm
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano-op-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano-op-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano-op.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/granapadano.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae-op-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae-op-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae-op.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greciliae.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/greextra.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregall.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio-op-hole.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio-op-hollow.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio-op.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gregorio.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/grelaon.ttf
%{_tl_texmf}/fonts/truetype/public/gregoriotex/gresgmodern.ttf
%{_tl_texmf}/fonts/type1/public/figbas/cmrj.pfb
%{_tl_texmf}/fonts/type1/public/figbas/cmssj.pfb
%{_tl_texmf}/fonts/type1/public/figbas/plrj.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/MuseJazzText.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/feta20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/frenchtab.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musix29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musixsps.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/musixspx.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/mxsk.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xadf29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xgreg29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xppff10.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld11d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld13d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld16d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld24d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsld29d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsldd20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xsldu20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd11d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd13d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd16d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd24d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhd29d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu11d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu13d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu16d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu24d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhu29d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhz20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslhz20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu11.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu11d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu13.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu13d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu16.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu16d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu24.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu24d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu29.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslu29d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslud20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslup20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslz20.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xslz20d.pfb
%{_tl_texmf}/fonts/type1/public/musixtex-fonts/xtie20.pfb
%{_tl_texmf}/makeindex/songbook/songbook.ist
%{_tl_texmf}/scripts/gregoriotex/uninstall-gtex.sh
%{_tl_texmf}/scripts/lilyglyphs/lily-glyph-commands.py
%{_tl_texmf}/scripts/lilyglyphs/lily-image-commands.py
%{_tl_texmf}/scripts/lilyglyphs/lily-rebuild-pdfs.py
%{_tl_texmf}/scripts/lilyglyphs/lilyglyphs_common.py
%{_tl_texmf}/scripts/lyluatex/lyluatex.lua
%{_tl_texmf}/scripts/musixtex/musixflx.bat
%{_tl_texmf}/scripts/musixtex/musixflx.lua
%{_tl_texmf}/scripts/musixtex/musixtex.bat
%{_tl_texmf}/scripts/musixtex/musixtex.lua
%{_tl_texmf}/scripts/pmxchords/ChordsTr.lua
%{_tl_texmf}/scripts/pmxchords/pmxchords.lua
%{_tl_texmf}/tex/generic/bagpipe/bagpipe.ini
%{_tl_texmf}/tex/generic/bagpipe/bagpipe.tex
%{_tl_texmf}/tex/generic/bagpipe/bagpipex.ini
%{_tl_texmf}/tex/generic/m-tx/mtx.tex
%{_tl_texmf}/tex/generic/musixtex/musixadd.tex
%{_tl_texmf}/tex/generic/musixtex/musixadf.tex
%{_tl_texmf}/tex/generic/musixtex/musixbar.tex
%{_tl_texmf}/tex/generic/musixtex/musixbbm.tex
%{_tl_texmf}/tex/generic/musixtex/musixblx.tex
%{_tl_texmf}/tex/generic/musixtex/musixbm.tex
%{_tl_texmf}/tex/generic/musixtex/musixcho.tex
%{_tl_texmf}/tex/generic/musixtex/musixcls.tex
%{_tl_texmf}/tex/generic/musixtex/musixcpt.tex
%{_tl_texmf}/tex/generic/musixtex/musixcrd.tex
%{_tl_texmf}/tex/generic/musixtex/musixdat.tex
%{_tl_texmf}/tex/generic/musixtex/musixdbr.tex
%{_tl_texmf}/tex/generic/musixtex/musixdia.tex
%{_tl_texmf}/tex/generic/musixtex/musixebgr.tex
%{_tl_texmf}/tex/generic/musixtex/musixec.tex
%{_tl_texmf}/tex/generic/musixtex/musixeng.tex
%{_tl_texmf}/tex/generic/musixtex/musixesf.tex
%{_tl_texmf}/tex/generic/musixtex/musixevo.tex
%{_tl_texmf}/tex/generic/musixtex/musixext.tex
%{_tl_texmf}/tex/generic/musixtex/musixfll.tex
%{_tl_texmf}/tex/generic/musixtex/musixftab.tex
%{_tl_texmf}/tex/generic/musixtex/musixgre.tex
%{_tl_texmf}/tex/generic/musixtex/musixgui.tex
%{_tl_texmf}/tex/generic/musixtex/musixhor.tex
%{_tl_texmf}/tex/generic/musixtex/musixhou.tex
%{_tl_texmf}/tex/generic/musixtex/musixhv.tex
%{_tl_texmf}/tex/generic/musixtex/musixinv.tex
%{_tl_texmf}/tex/generic/musixtex/musixjt.tex
%{_tl_texmf}/tex/generic/musixtex/musixlit.tex
%{_tl_texmf}/tex/generic/musixtex/musixlyr.tex
%{_tl_texmf}/tex/generic/musixtex/musixmad.tex
%{_tl_texmf}/tex/generic/musixtex/musixmkm.tex
%{_tl_texmf}/tex/generic/musixtex/musixmtab.tex
%{_tl_texmf}/tex/generic/musixtex/musixper.tex
%{_tl_texmf}/tex/generic/musixtex/musixplt.tex
%{_tl_texmf}/tex/generic/musixtex/musixpoi.tex
%{_tl_texmf}/tex/generic/musixtex/musixppff.tex
%{_tl_texmf}/tex/generic/musixtex/musixps.tex
%{_tl_texmf}/tex/generic/musixtex/musixref.tex
%{_tl_texmf}/tex/generic/musixtex/musixslu.tex
%{_tl_texmf}/tex/generic/musixtex/musixsqr.tex
%{_tl_texmf}/tex/generic/musixtex/musixste.tex
%{_tl_texmf}/tex/generic/musixtex/musixstf.tex
%{_tl_texmf}/tex/generic/musixtex/musixstr.tex
%{_tl_texmf}/tex/generic/musixtex/musixsty.tex
%{_tl_texmf}/tex/generic/musixtex/musixt1.def
%{_tl_texmf}/tex/generic/musixtex/musixtex.tex
%{_tl_texmf}/tex/generic/musixtex/musixthacc.tex
%{_tl_texmf}/tex/generic/musixtex/musixtmr.tex
%{_tl_texmf}/tex/generic/musixtex/musixtri.tex
%{_tl_texmf}/tex/generic/musixtex/musixvbm.tex
%{_tl_texmf}/tex/generic/musixtex/tuplet.tex
%{_tl_texmf}/tex/generic/musixtnt/musixtnt.tex
%{_tl_texmf}/tex/generic/pmx/pmx.tex
%{_tl_texmf}/tex/generic/pmxchords/chords.tex
%{_tl_texmf}/tex/generic/pmxchords/chordsCZ.tex
%{_tl_texmf}/tex/latex/abc/abc.sty
%{_tl_texmf}/tex/latex/abc/mup.sty
%{_tl_texmf}/tex/latex/chordbars/chordbars.sty
%{_tl_texmf}/tex/latex/chordbox/chordbox.sty
%{_tl_texmf}/tex/latex/ddphonism/ddphonism.sty
%{_tl_texmf}/tex/latex/fretplot/fretplot.lua
%{_tl_texmf}/tex/latex/fretplot/fretplot.sty
%{_tl_texmf}/tex/latex/gchords/gchords.sty
%{_tl_texmf}/tex/latex/gtrcrd/gtrcrd.sty
%{_tl_texmf}/tex/latex/guitar/guitar.sty
%{_tl_texmf}/tex/latex/guitarchordschemes/guitarchordschemes.sty
%{_tl_texmf}/tex/latex/guitartabs/guitartabs.cls
%{_tl_texmf}/tex/latex/harmony/harmony.sty
%{_tl_texmf}/tex/latex/leadsheets/leadsheet.cls
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.chordnames.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.chords.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.external.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.musejazz.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.musicsymbols.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.properties.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.shorthands.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.songs.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.templates.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.translations.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.library.transposing.code.tex
%{_tl_texmf}/tex/latex/leadsheets/leadsheets.sty
%{_tl_texmf}/tex/latex/liederbuch/liederbuch-babel.sty
%{_tl_texmf}/tex/latex/liederbuch/liederbuch-listofsongs.sty
%{_tl_texmf}/tex/latex/liederbuch/liederbuch.sty
%{_tl_texmf}/tex/latex/liederbuch/printliederbuch.sty
%{_tl_texmf}/tex/latex/lilyglyphs/README-tex
%{_tl_texmf}/tex/latex/lilyglyphs/commands/README-commands
%{_tl_texmf}/tex/latex/lilyglyphs/commands/accidentals.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/accordion.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/beamednotes.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/clefs.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/dynamics.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/fancyexamples.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/noteheads.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/numbers.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/rests.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/scripts.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/singlenotes.inp
%{_tl_texmf}/tex/latex/lilyglyphs/commands/timesignatures.inp
%{_tl_texmf}/tex/latex/lilyglyphs/core/README-core
%{_tl_texmf}/tex/latex/lilyglyphs/core/dotted.inp
%{_tl_texmf}/tex/latex/lilyglyphs/core/genericAccess.inp
%{_tl_texmf}/tex/latex/lilyglyphs/core/keyval.inp
%{_tl_texmf}/tex/latex/lilyglyphs/core/opticals.inp
%{_tl_texmf}/tex/latex/lilyglyphs/lilyglyphs.sty
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crescHairpin.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchet.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchetDotted.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchetDottedDouble.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchetDottedDoubleDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchetDottedDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-crotchetDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-decrescHairpin.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaver.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaverDotted.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaverDottedDouble.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaverDottedDoubleDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaverDottedDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-demisemiquaverDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-fancyExample.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNote.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNoteDotted.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNoteDottedDouble.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNoteDottedDoubleDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNoteDottedDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-halfNoteDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaver.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDotted.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDottedDouble.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDottedDoubleDdown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDottedDoubleDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDottedDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-quaverDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaver.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaverDotted.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaverDottedDouble.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaverDottedDoubleDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaverDottedDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-semiquaverDown.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-threeBeamedQuavers.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-threeBeamedQuaversI.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-threeBeamedQuaversII.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-threeBeamedQuaversIII.pdf
%{_tl_texmf}/tex/latex/lilyglyphs/pdfs/lily-twoBeamedQuavers.pdf
%{_tl_texmf}/tex/latex/m-tx/mtxlatex.sty
%{_tl_texmf}/tex/latex/mousik/mousik.sty
%{_tl_texmf}/tex/latex/musical/musical.sty
%{_tl_texmf}/tex/latex/musicography/musicography.sty
%{_tl_texmf}/tex/latex/musixguit/musixguit.sty
%{_tl_texmf}/tex/latex/musixtex/musixcpt.sty
%{_tl_texmf}/tex/latex/musixtex/musixcrd.sty
%{_tl_texmf}/tex/latex/musixtex/musixfll.sty
%{_tl_texmf}/tex/latex/musixtex/musixltx.tex
%{_tl_texmf}/tex/latex/musixtex/musixtex.sty
%{_tl_texmf}/tex/latex/octave/octave.sty
%{_tl_texmf}/tex/latex/piano/piano.sty
%{_tl_texmf}/tex/latex/recorder-fingering/recorder-fingering.sty
%{_tl_texmf}/tex/latex/songbook/conditionals.sty
%{_tl_texmf}/tex/latex/songbook/songbook.sty
%{_tl_texmf}/tex/latex/songproj/songproj.sty
%{_tl_texmf}/tex/latex/songs/songs.sty
%{_tl_texmf}/tex/latex/undar-digitacion/undar-digitacion.sty
%{_tl_texmf}/tex/latex/xpiano/xpiano.sty
%{_tl_texmf}/tex/lualatex/gregoriotex/gregoriosyms.sty
%{_tl_texmf}/tex/lualatex/gregoriotex/gregoriotex.sty
%{_tl_texmf}/tex/luatex/gregoriotex/gregorio-vowels.dat
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-chars.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-common.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-gsp-default.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-main.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-nabc.lua
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-nabc.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-signs.lua
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-signs.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-spaces.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-syllable.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-symbols.lua
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex-symbols.tex
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex.lua
%{_tl_texmf}/tex/luatex/gregoriotex/gregoriotex.tex
%{_tl_texmf}/tex/luatex/lyluatex/lyluatex.sty

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- rolled to tlnet snapshot 20260925 (36 members)
