# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-langenglish
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live langenglish collection — US and UK English
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/25/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live langenglish collection (US and UK English) — the texmf-dist data tree
from tlnet snapshot 20260925, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
hyphen-english
latexfileinfo-pkgs
macros2e
quran-en
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-en-gb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-en-us.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-en-gb.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-en-us.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-en-gb.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-en-gb.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-en-us.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-en-us.pat.txt
%{_tl_texmf}/tex/latex/latexfileinfo-pkgs/latexfileinfo_pkgs.RLS
%{_tl_texmf}/tex/latex/macros2e/extlabels.sty
%{_tl_texmf}/tex/xelatex/quran-en/quran-en.sty
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-eniii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-eniv.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enix.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-env.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-envi.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-envii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enviii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enx.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxi.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxiii.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxiv.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxv.translation.def
%{_tl_texmf}/tex/xelatex/quran-en/qurantext-enxvi.translation.def

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- rolled to tlnet snapshot 20260925 (4 members)
