# Generated by rust2rpm 28, adapted to this repo's conventions:
# spelled-out crates.io Source URL (mock fetches sources before buildroot
# macros exist), online cargo prep/license macros (anda-srpm-macros), tests
# disabled, explicit Release + changelog.
%undefine __brp_mangle_shebangs
%define debug_package %{nil}
# no debuginfo in the compiled objects either — nothing consumes it and it
# is a large share of compile time on big dependency trees
%define rustflags_debuginfo 0
%bcond check 0

%global crate uv

Name:           rust-uv
Version:        0.12.17
Release:        1%{?dist}
Summary:        Python package and project manager

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/uv
# the crates.io download URL spelled out: mock fetches sources at
# SRPM-build time, before the buildroot macros (anda-srpm-macros) exist
#!RemoteAsset
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate
#!RemoteAsset
Source1:        https://raw.githubusercontent.com/astral-sh/uv/%{version}/LICENSE-APACHE
#!RemoteAsset
Source2:        https://raw.githubusercontent.com/astral-sh/uv/%{version}/LICENSE-MIT

BuildRequires:  anda-srpm-macros
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  mold
# compilation cache server — its cache dir lives on the workspace via the
# mock config's bind mount, shared across all rust source builds
BuildRequires:  sccache
BuildRequires:  cmake

%global _description %{expand:
A Python package and project manager.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# aggregate of every linked crate's license, as carried by LICENSE.dependencies
License:        ((Apache-2.0 OR MIT) AND BSD-3-Clause) AND ((MIT OR Apache-2.0) AND Unicode-3.0) AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR BSD-2-Clause) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 OR MIT OR Zlib) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND (CC0-1.0 OR Apache-2.0 OR Apache-2.0 WITH LLVM-exception) AND (CC0-1.0 OR MIT-0 OR Apache-2.0) AND (ISC AND (Apache-2.0 OR ISC) AND Apache-2.0 AND MIT AND BSD-3-Clause AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 OR ISC OR MIT-0)) AND (ISC AND (Apache-2.0 OR ISC)) AND (LGPL-3.0-or-later OR MPL-2.0) AND (MIT OR Apache-2.0 OR LGPL-2.1-or-later) AND (MIT OR Apache-2.0) AND (MIT OR LGPL-3.0-or-later) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT) AND (Zlib OR Apache-2.0 OR MIT) AND 0BSD AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND CDLA-Permissive-2.0 AND ISC AND MIT AND MIT-0 AND MPL-2.0 AND Unicode-3.0 AND Zlib

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%{_bindir}/uv
%{_bindir}/uvx

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+axoupdater-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+axoupdater-devel %{_description}

This package contains library source intended for building other packages which
use the "axoupdater" feature of the "%{crate}" crate.

%files       -n %{name}+axoupdater-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-auth-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-auth-devel %{_description}

This package contains library source intended for building other packages which
use the "native-auth" feature of the "%{crate}" crate.

%files       -n %{name}+native-auth-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+performance-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+performance-devel %{_description}

This package contains library source intended for building other packages which
use the "performance" feature of the "%{crate}" crate.

%files       -n %{name}+performance-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+performance-memory-allocator-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+performance-memory-allocator-devel %{_description}

This package contains library source intended for building other packages which
use the "performance-memory-allocator" feature of the "%{crate}" crate.

%files       -n %{name}+performance-memory-allocator-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+self-update-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+self-update-devel %{_description}

This package contains library source intended for building other packages which
use the "self-update" feature of the "%{crate}" crate.

%files       -n %{name}+self-update-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-crates-io-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-crates-io-devel %{_description}

This package contains library source intended for building other packages which
use the "test-crates-io" feature of the "%{crate}" crate.

%files       -n %{name}+test-crates-io-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-defaults-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-defaults-devel %{_description}

This package contains library source intended for building other packages which
use the "test-defaults" feature of the "%{crate}" crate.

%files       -n %{name}+test-defaults-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-ecosystem-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-ecosystem-devel %{_description}

This package contains library source intended for building other packages which
use the "test-ecosystem" feature of the "%{crate}" crate.

%files       -n %{name}+test-ecosystem-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-git-devel %{_description}

This package contains library source intended for building other packages which
use the "test-git" feature of the "%{crate}" crate.

%files       -n %{name}+test-git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-git-lfs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-git-lfs-devel %{_description}

This package contains library source intended for building other packages which
use the "test-git-lfs" feature of the "%{crate}" crate.

%files       -n %{name}+test-git-lfs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-pypi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-pypi-devel %{_description}

This package contains library source intended for building other packages which
use the "test-pypi" feature of the "%{crate}" crate.

%files       -n %{name}+test-pypi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-python-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-python-devel %{_description}

This package contains library source intended for building other packages which
use the "test-python" feature of the "%{crate}" crate.

%files       -n %{name}+test-python-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-python-eol-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-python-eol-devel %{_description}

This package contains library source intended for building other packages which
use the "test-python-eol" feature of the "%{crate}" crate.

%files       -n %{name}+test-python-eol-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-python-managed-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-python-managed-devel %{_description}

This package contains library source intended for building other packages which
use the "test-python-managed" feature of the "%{crate}" crate.

%files       -n %{name}+test-python-managed-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-python-patch-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-python-patch-devel %{_description}

This package contains library source intended for building other packages which
use the "test-python-patch" feature of the "%{crate}" crate.

%files       -n %{name}+test-python-patch-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-r2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-r2-devel %{_description}

This package contains library source intended for building other packages which
use the "test-r2" feature of the "%{crate}" crate.

%files       -n %{name}+test-r2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-slow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-slow-devel %{_description}

This package contains library source intended for building other packages which
use the "test-slow" feature of the "%{crate}" crate.

%files       -n %{name}+test-slow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-universal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-universal-devel %{_description}

This package contains library source intended for building other packages which
use the "test-universal" feature of the "%{crate}" crate.

%files       -n %{name}+test-universal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-windows-registry-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-windows-registry-devel %{_description}

This package contains library source intended for building other packages which
use the "test-windows-registry" feature of the "%{crate}" crate.

%files       -n %{name}+test-windows-registry-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-durations-export-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-durations-export-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-durations-export" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-durations-export-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uv-test-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uv-test-devel %{_description}

This package contains library source intended for building other packages which
use the "uv-test" feature of the "%{crate}" crate.

%files       -n %{name}+uv-test-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+windows-gui-bin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+windows-gui-bin-devel %{_description}

This package contains library source intended for building other packages which
use the "windows-gui-bin" feature of the "%{crate}" crate.

%files       -n %{name}+windows-gui-bin-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online_sccache

%build
# cache dir on the workspace bind mount (see mock config) — survives across
# builds and is shared by every rust source build
export SCCACHE_DIR=/sccache
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
export SCCACHE_DIR=/sccache
%cargo_install -- --locked
cp %{S:1} %{S:2} .

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Sep 25 2026 ahsan <aahsnr041@proton.me> - 0.12.17-1
- source build with the terra rust2rpm macro set (was: prebuilt-binary
  wrapper over the release binary)

