# Wrapper over uv's official prebuilt musl release tarball (contains the uv
# and uvx executables). Shell completions are generated by running the
# binary at build time — the static musl binary runs anywhere.
Name:           uv
Version:        0.12.17
Release:        1%{?dist}
Summary:        An extremely fast Python package and project manager, written in Rust
License:        MIT OR Apache-2.0
URL:            https://docs.astral.sh/uv/
Source0:        https://github.com/astral-sh/uv/releases/download/%{version}/uv-x86_64-unknown-linux-musl.tar.gz

ExclusiveArch:  x86_64

%description
uv is an extremely fast Python package and project manager, written in Rust:
a drop-in replacement for pip/pip-tools/virtualenv/pipx and more.

%prep
%autosetup -n uv-x86_64-unknown-linux-musl

%install
install -Dpm755 uv %{buildroot}%{_bindir}/uv
install -Dpm755 uvx %{buildroot}%{_bindir}/uvx
./uv generate-shell-completions --shell bash > uv.bash
./uv generate-shell-completions --shell zsh > _uv
./uv generate-shell-completions --shell fish > uv.fish
install -Dpm644 uv.bash %{buildroot}%{_datadir}/bash-completion/completions/uv
install -Dpm644 _uv %{buildroot}%{_datadir}/zsh/site-functions/_uv
install -Dpm644 uv.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/uv.fish

%files
%{_bindir}/uv
%{_bindir}/uvx
%{_datadir}/bash-completion/completions/uv
%{_datadir}/zsh/site-functions/_uv
%{_datadir}/fish/vendor_completions.d/uv.fish
