#!/usr/bin/env python3
"""Adapt the splitter-generated spec into a buildable anda package spec.

The generated spec references the LOCAL install staging tree (absolute host
paths, %global _tl_staging/_tl_texmf). This script rewrites it into
anda/texlive-texmf/texlive-texmf.spec, which stages the snapshot itself at
%build time from the tlnet archive (mock chroot network is on — the same
pattern as the repo's cargo/npm/Go builds) and copies texmf-dist into the
buildroot in %install. Published to the Cloudflare R2 bucket by
ci/publish-r2.sh (scheme-full output is beyond the Pages budget).

Usage (after splitter.py has produced generated/texlive-texmf.spec):
  ./adapt-spec.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATED = Path(__file__).resolve().parent / "generated" / "texlive-texmf.spec"
OUT = ROOT / "anda" / "texlive-texmf" / "texlive-texmf.spec"

HEADER_TEMPLATE = """\
# GENERATED by tools/texlive-splitter from the tlnet-archive snapshot
# (python3 tools/texlive-splitter/splitter.py --snapshot __SNAPSHOT__
#  --scheme __SCHEME____DOCS_FLAG__ --tlpdb-only) and adapted by
# adapt-spec.py — do not edit by hand.
#
# The %files lists are relative to %_tl_texmf (= Fedora's texlive tree
# /usr/share/texlive/texmf-dist). The snapshot itself is staged at %build
# time from the archive URL — one snapshot for ALL groups (mock runs with
# network on, like the repo's cargo/npm/Go builds). Published to the R2
# bucket by ci/publish-r2.sh (this output is beyond the Pages budget).
Name:           texlive-texmf
Version:        __SNAPSHOT__
Release:        1%{?dist}
Summary:        TeX Live packages, Arch-style grouping (noarch data)
License:        GPL+ and others (TeX Live collective licenses)
BuildArch:      noarch

BuildRequires:  wget
BuildRequires:  perl
BuildRequires:  tar
BuildRequires:  gzip
BuildRequires:  xz
BuildRequires:  unzip

# the texmf tree root the subpackage %files hang off of
%global _tl_texmf %{_datadir}/texlive/texmf-dist
%global _tl_archive_url __ARCHIVE_ROOT__/tlnet
%global _tl_scheme __SCHEME__
%global _tl_option_doc __OPTION_DOC__

%description
TeX Live snapshot packages (splitter-generated, Arch-style grouping): the
texmf-dist data tree split into collection groups. Binaries (the bin/ tree)
and the format/map/hyphenation post-install fragments are follow-up splits.

%prep
# nothing to unpack — %build stages the snapshot from the archive

%build
# stage the whole snapshot from the dated archive (network is on in the mock
# chroot). One install for ALL groups keeps the set atomic.
mkdir -p %{_builddir}/tl-staging
cat > %{_builddir}/tl-staging/texlive.profile <<'PROFILE'
selected_scheme %{_tl_scheme}
TEXDIR %{_builddir}/tl-staging
TEXMFCONFIG %{_builddir}/tl-staging/texmf-config
TEXMFVAR %{_builddir}/tl-staging/texmf-var
TEXMFLOCAL %{_builddir}/tl-staging/texmf-local
TEXMFSYSCONFIG %{_builddir}/tl-staging/texmf-config
TEXMFSYSVAR %{_builddir}/tl-staging/texmf-var
option_doc %{_tl_option_doc}
option_src 0
instopt_adjustpath 0
instopt_adjustrepo 0
instopt_letter 0
instopt_portable 1
instopt_write18_restricted 1
tlpdbopt_autobackup 0
tlpdbopt_install_docfiles %{_tl_option_doc}
tlpdbopt_install_srcfiles 0
PROFILE
wget -q --retry-connrefused --waitretry=5 --tries=5 \\
    %{_tl_archive_url}/install-tl-unx.tar.gz -O %{_builddir}/install-tl-unx.tar.gz
tar -xzf %{_builddir}/install-tl-unx.tar.gz -C %{_builddir}
TEXLIVE_INSTALL_ENV_NOCREATE=1 \\
TEXLIVE_INSTALL_PREFIX=%{_builddir}/tl-staging \\
%{_builddir}/install-tl-*/install-tl \\
    --profile %{_builddir}/tl-staging/texlive.profile \\
    --repository %{_tl_archive_url}

%install
mkdir -p %{buildroot}%{_tl_texmf}
cp -a %{_builddir}/tl-staging/texmf-dist/. %{buildroot}%{_tl_texmf}/

%check
# the tree must be complete: install-tl writes its own manifest
test -f %{buildroot}%{_tl_texmf}/ls-R

"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--snapshot", default="20260901")
    ap.add_argument("--scheme", default="scheme-full")
    ap.add_argument(
        "--archive-root",
        default="https://texlive.info/tlnet-archive/2026/09/01",
        help="archive base WITHOUT the /tlnet suffix (a dated YYYY/MM/DD dir)",
    )
    ap.add_argument(
        "--no-docs", action="store_true",
        help="mirror a splitter run made with --no-docs (option_doc 0)",
    )
    args = ap.parse_args()
    option_doc = "0" if args.no_docs else "1"

    src = GENERATED.read_text()
    first_sub = src.index("%package -n ")
    blocks = src[first_sub:]

    header = (
        HEADER_TEMPLATE
        .replace("__SCHEME__", args.scheme)
        .replace("__SNAPSHOT__", args.snapshot)
        .replace("__ARCHIVE_ROOT__", args.archive_root)
        .replace("__OPTION_DOC__", option_doc)
        .replace("__DOCS_FLAG__", " --no-docs" if args.no_docs else "")
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + "\n" + blocks)
    (OUT.parent / "anda.hcl").write_text(
        "project pkg {\n"
        '\tarches = ["x86_64"]\n'
        "\trpm {\n"
        '\t\tspec = "texlive-texmf.spec"\n'
        "\t}\n"
        "}\n"
    )
    print(f"OK: wrote {OUT} ({len(blocks.splitlines())} subpackage lines)")


if __name__ == "__main__":
    main()
