# Generated by rust2rpm 28, adapted to this repo's conventions:
# spelled-out crates.io Source URL (mock fetches sources before buildroot
# macros exist), online cargo prep/license macros (anda-srpm-macros), tests
# disabled, explicit Release + changelog.
%undefine __brp_mangle_shebangs
%define debug_package %{nil}
# no debuginfo in the compiled objects either — nothing consumes it and it
# is a large share of compile time on big dependency trees
%define rustflags_debuginfo 0
%bcond check 0

%global crate atuin

Name:           rust-atuin
Version:        18.23.0
Release:        1%{?dist}
Summary:        Atuin - magical shell history

License:        MIT
URL:            https://crates.io/crates/atuin
# the crates.io download URL spelled out: mock fetches sources at
# SRPM-build time, before the buildroot macros (anda-srpm-macros) exist
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  anda-srpm-macros
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  mold
# compilation cache server — its cache dir lives on the workspace via the
# mock config's bind mount, shared across all rust source builds
BuildRequires:  sccache
# atuin's sync client pulls in native-tls, which links the system OpenSSL
BuildRequires:  pkgconfig(openssl)

%global _description %{expand:
Atuin - magical shell history.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# aggregate of every linked crate's license, as carried by LICENSE.dependencies
License:        ((Apache-2.0 OR MIT) AND BSD-3-Clause) AND ((MIT OR Apache-2.0) AND Unicode-3.0) AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 AND ISC) AND (Apache-2.0 OR BSL-1.0 OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR GPL-2.0-only) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0) AND (MIT AND (MIT OR Apache-2.0)) AND (MIT AND BSD-3-Clause) AND (MIT OR Apache-2.0 OR BSD-1-Clause) AND (MIT OR Apache-2.0 OR CC0-1.0) AND (MIT OR Apache-2.0 OR LGPL-2.1-or-later) AND (MIT OR Apache-2.0 OR Zlib) AND (MIT OR Apache-2.0) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT) AND (Zlib OR Apache-2.0 OR MIT) AND 0BSD AND Apache-2.0 AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND ISC AND MIT AND MPL-2.0 AND Unicode-3.0 AND Zlib

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/atuin


%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online_sccache

%build
# cache dir on the workspace bind mount (see mock config) — survives across
# builds and is shared by every rust source build
export SCCACHE_DIR=/sccache
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
export SCCACHE_DIR=/sccache
%cargo_install -- --locked

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Sep 25 2026 ahsan <aahsnr041@proton.me> - 18.23.0-1
- source build with the terra rust2rpm macro set (was: prebuilt-binary
  wrapper over the release binary)

