# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-langpolish
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live langpolish collection — Polish
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/25/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}
Requires:       texlive-latex = %{version}

%description
TeX Live langpolish collection (Polish) — the texmf-dist data tree
from tlnet snapshot 20260925, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
babel-polish
bredzenie
cc-pl
gustlib
hyphen-polish
mex
mwcls
pl
polski
przechlewski-book
qpxqtx
tap
utf8mex
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/bibtex/bib/gustlib/plbib.bib
%{_tl_texmf}/bibtex/bst/gustlib/plabbrv.bst
%{_tl_texmf}/bibtex/bst/gustlib/plalpha.bst
%{_tl_texmf}/bibtex/bst/gustlib/plplain.bst
%{_tl_texmf}/bibtex/bst/gustlib/plunsrt.bst
%{_tl_texmf}/bibtex/bst/przechlewski-book/papalike.bst
%{_tl_texmf}/dvips/pl/config.pl
%{_tl_texmf}/fonts/afm/public/pl/plb10.afm
%{_tl_texmf}/fonts/afm/public/pl/plbsy10.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx10.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx12.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx5.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx6.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx7.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx8.afm
%{_tl_texmf}/fonts/afm/public/pl/plbx9.afm
%{_tl_texmf}/fonts/afm/public/pl/plbxsl10.afm
%{_tl_texmf}/fonts/afm/public/pl/plbxti10.afm
%{_tl_texmf}/fonts/afm/public/pl/plcsc10.afm
%{_tl_texmf}/fonts/afm/public/pl/pldunh10.afm
%{_tl_texmf}/fonts/afm/public/pl/plex10.afm
%{_tl_texmf}/fonts/afm/public/pl/plex9.afm
%{_tl_texmf}/fonts/afm/public/pl/plff10.afm
%{_tl_texmf}/fonts/afm/public/pl/plfi10.afm
%{_tl_texmf}/fonts/afm/public/pl/plfib8.afm
%{_tl_texmf}/fonts/afm/public/pl/plinch.afm
%{_tl_texmf}/fonts/afm/public/pl/plitt10.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi10.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi12.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi5.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi6.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi7.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi8.afm
%{_tl_texmf}/fonts/afm/public/pl/plmi9.afm
%{_tl_texmf}/fonts/afm/public/pl/plmib10.afm
%{_tl_texmf}/fonts/afm/public/pl/plr10.afm
%{_tl_texmf}/fonts/afm/public/pl/plr12.afm
%{_tl_texmf}/fonts/afm/public/pl/plr17.afm
%{_tl_texmf}/fonts/afm/public/pl/plr5.afm
%{_tl_texmf}/fonts/afm/public/pl/plr6.afm
%{_tl_texmf}/fonts/afm/public/pl/plr7.afm
%{_tl_texmf}/fonts/afm/public/pl/plr8.afm
%{_tl_texmf}/fonts/afm/public/pl/plr9.afm
%{_tl_texmf}/fonts/afm/public/pl/plsl10.afm
%{_tl_texmf}/fonts/afm/public/pl/plsl12.afm
%{_tl_texmf}/fonts/afm/public/pl/plsl8.afm
%{_tl_texmf}/fonts/afm/public/pl/plsl9.afm
%{_tl_texmf}/fonts/afm/public/pl/plsltt10.afm
%{_tl_texmf}/fonts/afm/public/pl/plss10.afm
%{_tl_texmf}/fonts/afm/public/pl/plss12.afm
%{_tl_texmf}/fonts/afm/public/pl/plss17.afm
%{_tl_texmf}/fonts/afm/public/pl/plss8.afm
%{_tl_texmf}/fonts/afm/public/pl/plss9.afm
%{_tl_texmf}/fonts/afm/public/pl/plssbi10.afm
%{_tl_texmf}/fonts/afm/public/pl/plssbx10.afm
%{_tl_texmf}/fonts/afm/public/pl/plssdc10.afm
%{_tl_texmf}/fonts/afm/public/pl/plssi10.afm
%{_tl_texmf}/fonts/afm/public/pl/plssi12.afm
%{_tl_texmf}/fonts/afm/public/pl/plssi17.afm
%{_tl_texmf}/fonts/afm/public/pl/plssi8.afm
%{_tl_texmf}/fonts/afm/public/pl/plssi9.afm
%{_tl_texmf}/fonts/afm/public/pl/plssq8.afm
%{_tl_texmf}/fonts/afm/public/pl/plssqi8.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy10.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy5.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy6.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy7.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy8.afm
%{_tl_texmf}/fonts/afm/public/pl/plsy9.afm
%{_tl_texmf}/fonts/afm/public/pl/pltcsc10.afm
%{_tl_texmf}/fonts/afm/public/pl/pltex10.afm
%{_tl_texmf}/fonts/afm/public/pl/pltex8.afm
%{_tl_texmf}/fonts/afm/public/pl/pltex9.afm
%{_tl_texmf}/fonts/afm/public/pl/plti10.afm
%{_tl_texmf}/fonts/afm/public/pl/plti12.afm
%{_tl_texmf}/fonts/afm/public/pl/plti7.afm
%{_tl_texmf}/fonts/afm/public/pl/plti8.afm
%{_tl_texmf}/fonts/afm/public/pl/plti9.afm
%{_tl_texmf}/fonts/afm/public/pl/pltt10.afm
%{_tl_texmf}/fonts/afm/public/pl/pltt12.afm
%{_tl_texmf}/fonts/afm/public/pl/pltt8.afm
%{_tl_texmf}/fonts/afm/public/pl/pltt9.afm
%{_tl_texmf}/fonts/afm/public/pl/plu10.afm
%{_tl_texmf}/fonts/afm/public/pl/plvtt10.afm
%{_tl_texmf}/fonts/enc/dvips/pl/plin.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plit.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plitt.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plme.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plmi.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plms.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plrm.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plsc.enc
%{_tl_texmf}/fonts/enc/dvips/pl/plte.enc
%{_tl_texmf}/fonts/enc/dvips/pl/pltt.enc
%{_tl_texmf}/fonts/map/dvips/cc-pl/ccpl.map
%{_tl_texmf}/fonts/map/dvips/pl/plother.map
%{_tl_texmf}/fonts/map/dvips/pl/pltext.map
%{_tl_texmf}/fonts/source/public/cc-pl/fic_mic.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pccsc10.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcmi10.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr10.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr5.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr6.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr7.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr8.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcr9.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcsl10.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcslc9.mf
%{_tl_texmf}/fonts/source/public/cc-pl/pcti10.mf
%{_tl_texmf}/fonts/source/public/pl/cmssbi10.mf
%{_tl_texmf}/fonts/source/public/pl/dlr10.mf
%{_tl_texmf}/fonts/source/public/pl/fik_mik.mf
%{_tl_texmf}/fonts/source/public/pl/pl.mft
%{_tl_texmf}/fonts/source/public/pl/pl_cud.mf
%{_tl_texmf}/fonts/source/public/pl/pl_dl.mf
%{_tl_texmf}/fonts/source/public/pl/pl_dod.mf
%{_tl_texmf}/fonts/source/public/pl/pl_ml.mf
%{_tl_texmf}/fonts/source/public/pl/pl_mlk.mf
%{_tl_texmf}/fonts/source/public/pl/pl_sym.mf
%{_tl_texmf}/fonts/source/public/pl/plb10.mf
%{_tl_texmf}/fonts/source/public/pl/plbsy10.mf
%{_tl_texmf}/fonts/source/public/pl/plbsy5.mf
%{_tl_texmf}/fonts/source/public/pl/plbsy7.mf
%{_tl_texmf}/fonts/source/public/pl/plbx10.mf
%{_tl_texmf}/fonts/source/public/pl/plbx12.mf
%{_tl_texmf}/fonts/source/public/pl/plbx5.mf
%{_tl_texmf}/fonts/source/public/pl/plbx6.mf
%{_tl_texmf}/fonts/source/public/pl/plbx7.mf
%{_tl_texmf}/fonts/source/public/pl/plbx8.mf
%{_tl_texmf}/fonts/source/public/pl/plbx9.mf
%{_tl_texmf}/fonts/source/public/pl/plbxsl10.mf
%{_tl_texmf}/fonts/source/public/pl/plbxti10.mf
%{_tl_texmf}/fonts/source/public/pl/plcsc10.mf
%{_tl_texmf}/fonts/source/public/pl/pldunh10.mf
%{_tl_texmf}/fonts/source/public/pl/plex10.mf
%{_tl_texmf}/fonts/source/public/pl/plff10.mf
%{_tl_texmf}/fonts/source/public/pl/plfi10.mf
%{_tl_texmf}/fonts/source/public/pl/plfib8.mf
%{_tl_texmf}/fonts/source/public/pl/plinch.mf
%{_tl_texmf}/fonts/source/public/pl/plitt10.mf
%{_tl_texmf}/fonts/source/public/pl/plmi10.mf
%{_tl_texmf}/fonts/source/public/pl/plmi12.mf
%{_tl_texmf}/fonts/source/public/pl/plmi5.mf
%{_tl_texmf}/fonts/source/public/pl/plmi6.mf
%{_tl_texmf}/fonts/source/public/pl/plmi7.mf
%{_tl_texmf}/fonts/source/public/pl/plmi8.mf
%{_tl_texmf}/fonts/source/public/pl/plmi9.mf
%{_tl_texmf}/fonts/source/public/pl/plmib10.mf
%{_tl_texmf}/fonts/source/public/pl/plmib5.mf
%{_tl_texmf}/fonts/source/public/pl/plmib7.mf
%{_tl_texmf}/fonts/source/public/pl/plr10.mf
%{_tl_texmf}/fonts/source/public/pl/plr12.mf
%{_tl_texmf}/fonts/source/public/pl/plr17.mf
%{_tl_texmf}/fonts/source/public/pl/plr5.mf
%{_tl_texmf}/fonts/source/public/pl/plr6.mf
%{_tl_texmf}/fonts/source/public/pl/plr7.mf
%{_tl_texmf}/fonts/source/public/pl/plr8.mf
%{_tl_texmf}/fonts/source/public/pl/plr9.mf
%{_tl_texmf}/fonts/source/public/pl/plsl10.mf
%{_tl_texmf}/fonts/source/public/pl/plsl12.mf
%{_tl_texmf}/fonts/source/public/pl/plsl8.mf
%{_tl_texmf}/fonts/source/public/pl/plsl9.mf
%{_tl_texmf}/fonts/source/public/pl/plsltt10.mf
%{_tl_texmf}/fonts/source/public/pl/plss10.mf
%{_tl_texmf}/fonts/source/public/pl/plss12.mf
%{_tl_texmf}/fonts/source/public/pl/plss17.mf
%{_tl_texmf}/fonts/source/public/pl/plss8.mf
%{_tl_texmf}/fonts/source/public/pl/plss9.mf
%{_tl_texmf}/fonts/source/public/pl/plssbi10.mf
%{_tl_texmf}/fonts/source/public/pl/plssbx10.mf
%{_tl_texmf}/fonts/source/public/pl/plssdc10.mf
%{_tl_texmf}/fonts/source/public/pl/plssi10.mf
%{_tl_texmf}/fonts/source/public/pl/plssi12.mf
%{_tl_texmf}/fonts/source/public/pl/plssi17.mf
%{_tl_texmf}/fonts/source/public/pl/plssi8.mf
%{_tl_texmf}/fonts/source/public/pl/plssi9.mf
%{_tl_texmf}/fonts/source/public/pl/plssq8.mf
%{_tl_texmf}/fonts/source/public/pl/plssqi8.mf
%{_tl_texmf}/fonts/source/public/pl/plsy10.mf
%{_tl_texmf}/fonts/source/public/pl/plsy5.mf
%{_tl_texmf}/fonts/source/public/pl/plsy6.mf
%{_tl_texmf}/fonts/source/public/pl/plsy7.mf
%{_tl_texmf}/fonts/source/public/pl/plsy8.mf
%{_tl_texmf}/fonts/source/public/pl/plsy9.mf
%{_tl_texmf}/fonts/source/public/pl/pltcsc10.mf
%{_tl_texmf}/fonts/source/public/pl/pltex10.mf
%{_tl_texmf}/fonts/source/public/pl/pltex8.mf
%{_tl_texmf}/fonts/source/public/pl/pltex9.mf
%{_tl_texmf}/fonts/source/public/pl/plti10.mf
%{_tl_texmf}/fonts/source/public/pl/plti12.mf
%{_tl_texmf}/fonts/source/public/pl/plti7.mf
%{_tl_texmf}/fonts/source/public/pl/plti8.mf
%{_tl_texmf}/fonts/source/public/pl/plti9.mf
%{_tl_texmf}/fonts/source/public/pl/pltt10.mf
%{_tl_texmf}/fonts/source/public/pl/pltt12.mf
%{_tl_texmf}/fonts/source/public/pl/pltt8.mf
%{_tl_texmf}/fonts/source/public/pl/pltt9.mf
%{_tl_texmf}/fonts/source/public/pl/plu10.mf
%{_tl_texmf}/fonts/source/public/pl/plvtt10.mf
%{_tl_texmf}/fonts/source/public/pl/polan.mf
%{_tl_texmf}/fonts/source/public/pl/polkap.mf
%{_tl_texmf}/fonts/source/public/pl/polkur.mf
%{_tl_texmf}/fonts/source/public/pl/polmat.mf
%{_tl_texmf}/fonts/source/public/pl/poltyt.mf
%{_tl_texmf}/fonts/tfm/public/cc-pl/pccsc10.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcmi10.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr10.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr5.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr6.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr7.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr8.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcr9.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcsl10.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcslc9.tfm
%{_tl_texmf}/fonts/tfm/public/cc-pl/pcti10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plb10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbsy10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbsy5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbsy7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx6.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbx9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbxsl10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plbxti10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plcsc10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pldunh10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plex10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plex9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plff10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plfi10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plfib8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plinch.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plitt10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi6.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmi9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmib10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmib5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plmib7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr17.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr6.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plr9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsl10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsl12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsl8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsl9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsltt10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plss10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plss12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plss17.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plss8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plss9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssbi10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssbx10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssdc10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssi10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssi12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssi17.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssi8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssi9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssq8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plssqi8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy5.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy6.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plsy9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltcsc10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltex10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltex8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltex9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plti10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plti12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plti7.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plti8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plti9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltt10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltt12.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltt8.tfm
%{_tl_texmf}/fonts/tfm/public/pl/pltt9.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plu10.tfm
%{_tl_texmf}/fonts/tfm/public/pl/plvtt10.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qpxbmi.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qpxbmia.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qpxmi.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qpxmia.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qtxbmi.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qtxbmia.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qtxmi.tfm
%{_tl_texmf}/fonts/tfm/public/qpxqtx/qtxmia.tfm
%{_tl_texmf}/fonts/type1/public/cc-pl/pccsc10.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcmi10.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr10.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr5.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr6.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr7.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr8.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcr9.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcsl10.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcslc9.pfb
%{_tl_texmf}/fonts/type1/public/cc-pl/pcti10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plb10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plb10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbsy10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbsy10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx5.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx5.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx6.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx6.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx7.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx7.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbx9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbx9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbxsl10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbxsl10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plbxti10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plbxti10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plcsc10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plcsc10.pfm
%{_tl_texmf}/fonts/type1/public/pl/pldunh10.pfb
%{_tl_texmf}/fonts/type1/public/pl/pldunh10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plex10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plex10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plex9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plex9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plff10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plff10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plfi10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plfi10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plfib8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plfib8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plinch.pfb
%{_tl_texmf}/fonts/type1/public/pl/plinch.pfm
%{_tl_texmf}/fonts/type1/public/pl/plitt10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plitt10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi5.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi5.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi6.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi6.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi7.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi7.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmi9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmi9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plmib10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plmib10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr17.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr17.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr5.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr5.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr6.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr6.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr7.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr7.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plr9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plr9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsl10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsl10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsl12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsl12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsl8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsl8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsl9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsl9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsltt10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsltt10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plss10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plss10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plss12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plss12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plss17.pfb
%{_tl_texmf}/fonts/type1/public/pl/plss17.pfm
%{_tl_texmf}/fonts/type1/public/pl/plss8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plss8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plss9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plss9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssbi10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssbi10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssbx10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssbx10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssdc10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssdc10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssi10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssi10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssi12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssi12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssi17.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssi17.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssi8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssi8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssi9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssi9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssq8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssq8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plssqi8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plssqi8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy5.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy5.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy6.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy6.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy7.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy7.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plsy9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plsy9.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltcsc10.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltcsc10.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltex10.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltex10.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltex8.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltex8.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltex9.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltex9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plti10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plti10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plti12.pfb
%{_tl_texmf}/fonts/type1/public/pl/plti12.pfm
%{_tl_texmf}/fonts/type1/public/pl/plti7.pfb
%{_tl_texmf}/fonts/type1/public/pl/plti7.pfm
%{_tl_texmf}/fonts/type1/public/pl/plti8.pfb
%{_tl_texmf}/fonts/type1/public/pl/plti8.pfm
%{_tl_texmf}/fonts/type1/public/pl/plti9.pfb
%{_tl_texmf}/fonts/type1/public/pl/plti9.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltt10.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltt10.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltt12.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltt12.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltt8.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltt8.pfm
%{_tl_texmf}/fonts/type1/public/pl/pltt9.pfb
%{_tl_texmf}/fonts/type1/public/pl/pltt9.pfm
%{_tl_texmf}/fonts/type1/public/pl/plu10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plu10.pfm
%{_tl_texmf}/fonts/type1/public/pl/plvtt10.pfb
%{_tl_texmf}/fonts/type1/public/pl/plvtt10.pfm
%{_tl_texmf}/fonts/vf/public/qpxqtx/qpxbmi.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qpxbmia.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qpxmi.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qpxmia.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qtxbmi.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qtxbmia.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qtxmi.vf
%{_tl_texmf}/fonts/vf/public/qpxqtx/qtxmia.vf
%{_tl_texmf}/tex/generic/babel-polish/polish-compat.ldf
%{_tl_texmf}/tex/generic/babel-polish/polish.ldf
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-pl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-pl.qx.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-pl.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-pl.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-pl.pat.txt
%{_tl_texmf}/tex/generic/qpxqtx/amspbold.tex
%{_tl_texmf}/tex/generic/qpxqtx/amsqpx.def
%{_tl_texmf}/tex/generic/qpxqtx/amsqpx.tex
%{_tl_texmf}/tex/generic/qpxqtx/amsqtx.def
%{_tl_texmf}/tex/generic/qpxqtx/amsqtx.tex
%{_tl_texmf}/tex/generic/qpxqtx/amstbold.tex
%{_tl_texmf}/tex/generic/qpxqtx/qpxmath.sty
%{_tl_texmf}/tex/generic/qpxqtx/qpxmath.tex
%{_tl_texmf}/tex/generic/qpxqtx/qtxmath.sty
%{_tl_texmf}/tex/generic/qpxqtx/qtxmath.tex
%{_tl_texmf}/tex/generic/tap/tap.tex
%{_tl_texmf}/tex/latex/bredzenie/bredzenie.sty
%{_tl_texmf}/tex/latex/mwcls/mw10.clo
%{_tl_texmf}/tex/latex/mwcls/mw11.clo
%{_tl_texmf}/tex/latex/mwcls/mw12.clo
%{_tl_texmf}/tex/latex/mwcls/mwart.cls
%{_tl_texmf}/tex/latex/mwcls/mwbk.cls
%{_tl_texmf}/tex/latex/mwcls/mwbk10.clo
%{_tl_texmf}/tex/latex/mwcls/mwbk11.clo
%{_tl_texmf}/tex/latex/mwcls/mwbk12.clo
%{_tl_texmf}/tex/latex/mwcls/mwrep.cls
%{_tl_texmf}/tex/latex/polski/amigapl.def
%{_tl_texmf}/tex/latex/polski/mazovia.def
%{_tl_texmf}/tex/latex/polski/omlplcm.fd
%{_tl_texmf}/tex/latex/polski/omlplm.fd
%{_tl_texmf}/tex/latex/polski/omsplsy.fd
%{_tl_texmf}/tex/latex/polski/omxplex.fd
%{_tl_texmf}/tex/latex/polski/ot1patch.sty
%{_tl_texmf}/tex/latex/polski/ot4ccr.fd
%{_tl_texmf}/tex/latex/polski/ot4cmdh.fd
%{_tl_texmf}/tex/latex/polski/ot4cmfib.fd
%{_tl_texmf}/tex/latex/polski/ot4cmfr.fd
%{_tl_texmf}/tex/latex/polski/ot4cmr.fd
%{_tl_texmf}/tex/latex/polski/ot4cmss.fd
%{_tl_texmf}/tex/latex/polski/ot4cmtt.fd
%{_tl_texmf}/tex/latex/polski/plprefix.sty
%{_tl_texmf}/tex/latex/polski/polski.sty
%{_tl_texmf}/tex/latex/polski/qxenc.def
%{_tl_texmf}/tex/latex/przechlewski-book/upmgr.cls
%{_tl_texmf}/tex/latex/przechlewski-book/wkmgr.cls
%{_tl_texmf}/tex/mex/base/lamex.tex
%{_tl_texmf}/tex/mex/base/mex.tex
%{_tl_texmf}/tex/mex/base/mex1.tex
%{_tl_texmf}/tex/mex/base/mex2.tex
%{_tl_texmf}/tex/mex/base/mexconf.tex
%{_tl_texmf}/tex/mex/config/mex.ini
%{_tl_texmf}/tex/mex/config/pdfmex.ini
%{_tl_texmf}/tex/mex/utf8mex/utf8-pl.tex
%{_tl_texmf}/tex/mex/utf8mex/utf8mex.ini
%{_tl_texmf}/tex/mex/utf8mex/utf8plsq.tex
%{_tl_texmf}/tex/plain/gustlib/biblotex/biblotex.tex
%{_tl_texmf}/tex/plain/gustlib/infr-ex.tex
%{_tl_texmf}/tex/plain/gustlib/infram.tex
%{_tl_texmf}/tex/plain/gustlib/licz/licz-tst.mex
%{_tl_texmf}/tex/plain/gustlib/licz/licz.mex
%{_tl_texmf}/tex/plain/gustlib/map/map.tex
%{_tl_texmf}/tex/plain/gustlib/map/split.tex
%{_tl_texmf}/tex/plain/gustlib/map/tsp-tst.mex
%{_tl_texmf}/tex/plain/gustlib/map/tsp.tex
%{_tl_texmf}/tex/plain/gustlib/map/tun-test.mex
%{_tl_texmf}/tex/plain/gustlib/map/tun.tex
%{_tl_texmf}/tex/plain/gustlib/mcol-ex.tex
%{_tl_texmf}/tex/plain/gustlib/meashor.tex
%{_tl_texmf}/tex/plain/gustlib/mimulcol.tex
%{_tl_texmf}/tex/plain/gustlib/plbtx993/plbtxbst.doc
%{_tl_texmf}/tex/plain/gustlib/plbtx993/test.mex
%{_tl_texmf}/tex/plain/gustlib/plmac218/plidxmac.tex
%{_tl_texmf}/tex/plain/gustlib/plmac218/plind.bat
%{_tl_texmf}/tex/plain/gustlib/plmac218/przyklad.tex
%{_tl_texmf}/tex/plain/gustlib/rbox-ex.tex
%{_tl_texmf}/tex/plain/gustlib/roundbox.tex
%{_tl_texmf}/tex/plain/gustlib/tp-crf.tex
%{_tl_texmf}/tex/plain/gustlib/verbatim-dek.tex

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- rolled to tlnet snapshot 20260925 (13 members)
