# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260926 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-langgerman
Version:        20260926
Release:        1%{?dist}
Summary:        TeX Live langgerman collection — German
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/26/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}

%description
TeX Live langgerman collection (German) — the texmf-dist data tree
from tlnet snapshot 20260926, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
apalike-german
autotype
babel-german
bibleref-german
dehyph
dehyph-exptl
dhua
dtk-bibliography
fragoli
german
germbib
germkorr
hausarbeit-jura
hyphen-german
milog
quran-de
r_und_s
schulmathematik
termcal-de
udesoftec
uhrzeit
umlaute
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# upstream scripts carry pre-usrmerge shebangs (#!/bin/python3 and friends);
# the shebang mangler is disabled, so rpm would emit unresolvable file
# dependencies — normalize them to /usr/bin
find staging/texmf-dist -type f -exec sed -i '1s|^#!/bin/|#!/usr/bin/|' {} + 2>/dev/null || true
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/bibtex/bib/dtk-bibliography/dtk-bibliography.bib
%{_tl_texmf}/bibtex/bst/apalike-german/apalike-german.bst
%{_tl_texmf}/bibtex/bst/germbib/gerabbrv.bst
%{_tl_texmf}/bibtex/bst/germbib/geralpha.bst
%{_tl_texmf}/bibtex/bst/germbib/gerapali.bst
%{_tl_texmf}/bibtex/bst/germbib/gerplain.bst
%{_tl_texmf}/bibtex/bst/germbib/gerunsrt.bst
%{_tl_texmf}/bibtex/bst/udesoftec/udesoftec.bst
%{_tl_texmf}/tex/generic/babel-german/austrian.ldf
%{_tl_texmf}/tex/generic/babel-german/babel-german.def
%{_tl_texmf}/tex/generic/babel-german/german-at-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-at.ldf
%{_tl_texmf}/tex/generic/babel-german/german-austria-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-austria.ldf
%{_tl_texmf}/tex/generic/babel-german/german-ch-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-ch.ldf
%{_tl_texmf}/tex/generic/babel-german/german-de-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-de.ldf
%{_tl_texmf}/tex/generic/babel-german/german-germany-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-germany.ldf
%{_tl_texmf}/tex/generic/babel-german/german-switzerland-1901.ldf
%{_tl_texmf}/tex/generic/babel-german/german-switzerland.ldf
%{_tl_texmf}/tex/generic/babel-german/german.ldf
%{_tl_texmf}/tex/generic/babel-german/germanb.ldf
%{_tl_texmf}/tex/generic/babel-german/naustrian.ldf
%{_tl_texmf}/tex/generic/babel-german/ngerman.ldf
%{_tl_texmf}/tex/generic/babel-german/ngermanb.ldf
%{_tl_texmf}/tex/generic/babel-german/nswissgerman.ldf
%{_tl_texmf}/tex/generic/babel-german/swissgerman.ldf
%{_tl_texmf}/tex/generic/dehyph-exptl/dehyphn-x-2024-02-28.pat
%{_tl_texmf}/tex/generic/dehyph-exptl/dehyphn-x-2024-02-28.tex
%{_tl_texmf}/tex/generic/dehyph-exptl/dehypht-x-2024-02-28.pat
%{_tl_texmf}/tex/generic/dehyph-exptl/dehypht-x-2024-02-28.tex
%{_tl_texmf}/tex/generic/dehyph-exptl/dehyphts-x-2024-02-28.pat
%{_tl_texmf}/tex/generic/dehyph-exptl/dehyphts-x-2024-02-28.tex
%{_tl_texmf}/tex/generic/dehyph/README
%{_tl_texmf}/tex/generic/dehyph/dehyphn.tex
%{_tl_texmf}/tex/generic/dehyph/dehypht.tex
%{_tl_texmf}/tex/generic/dehyph/dehyphtex.tex
%{_tl_texmf}/tex/generic/german/german.sty
%{_tl_texmf}/tex/generic/german/ngerman.sty
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1901.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1996.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-de-ch-1901.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-de-1901.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-de-1996.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-de-ch-1901.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-de-1901.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-de-1996.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-de-ch-1901.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-de-1901.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-de-1996.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-de-ch-1901.pat.txt
%{_tl_texmf}/tex/latex/bibleref-german/bibleref-german.sty
%{_tl_texmf}/tex/latex/dhua/dhua.cfg
%{_tl_texmf}/tex/latex/dhua/dhua.sty
%{_tl_texmf}/tex/latex/dtk-bibliography/dtk-authoryear.bbx
%{_tl_texmf}/tex/latex/dtk-bibliography/dtk-authoryear.dbx
%{_tl_texmf}/tex/latex/dtk-bibliography/dtk-logos.sty
%{_tl_texmf}/tex/latex/fragoli/fragoli.sty
%{_tl_texmf}/tex/latex/germbib/bibgerm.sty
%{_tl_texmf}/tex/latex/germbib/mynormal.sty
%{_tl_texmf}/tex/latex/germkorr/germkorr.sty
%{_tl_texmf}/tex/latex/hausarbeit-jura/hausarbeit-jura.cls
%{_tl_texmf}/tex/latex/milog/milog.cls
%{_tl_texmf}/tex/latex/r_und_s/eng_rs.sty
%{_tl_texmf}/tex/latex/r_und_s/eng_rs.tex
%{_tl_texmf}/tex/latex/r_und_s/fr_rs.sty
%{_tl_texmf}/tex/latex/r_und_s/fr_rs.tex
%{_tl_texmf}/tex/latex/r_und_s/nl_rs.sty
%{_tl_texmf}/tex/latex/r_und_s/nl_rs.tex
%{_tl_texmf}/tex/latex/r_und_s/r_und_s.sty
%{_tl_texmf}/tex/latex/r_und_s/r_und_s.tex
%{_tl_texmf}/tex/latex/schulmathematik/schulma-ab.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma-gutachten.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma-klausur.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma-komp.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma-mdlprf.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma-physik.sty
%{_tl_texmf}/tex/latex/schulmathematik/schulma-praes.cls
%{_tl_texmf}/tex/latex/schulmathematik/schulma.sty
%{_tl_texmf}/tex/latex/termcal-de/termcal-de.sty
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-bibcommon.sty
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-biblatex.sty
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-bst.sty
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-cover-uba.pdf
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-cover-ude-de.pdf
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-cover-ude-en.pdf
%{_tl_texmf}/tex/latex/udesoftec/udesoftec-extra.sty
%{_tl_texmf}/tex/latex/udesoftec/udesoftec.cls
%{_tl_texmf}/tex/latex/uhrzeit/uhrzeit.sty
%{_tl_texmf}/tex/latex/umlaute/atari.def
%{_tl_texmf}/tex/latex/umlaute/isolatin.def
%{_tl_texmf}/tex/latex/umlaute/mac.def
%{_tl_texmf}/tex/latex/umlaute/pc850.def
%{_tl_texmf}/tex/latex/umlaute/roman8.def
%{_tl_texmf}/tex/latex/umlaute/umlaute.sty
%{_tl_texmf}/tex/lualatex/autotype/autotype-cls_pdnm_oop.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype-cls_pdnm_pattern.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype-cls_pdnm_spot.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype-cls_pdnm_trie_simple.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-primary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-primary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-secondary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-secondary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-special.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1901-special.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1996-primary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1996-primary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1996-secondary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-1996-secondary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-CH-1901-primary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-CH-1901-primary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-CH-1901-secondary.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-hyph-de-CH-1901-secondary.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-liga-de.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-liga-de.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-pdnm_nl_manipulation.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype-round-s-de.lic.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype-round-s-de.pat.txt
%{_tl_texmf}/tex/lualatex/autotype/autotype.lua
%{_tl_texmf}/tex/lualatex/autotype/autotype.sty
%{_tl_texmf}/tex/xelatex/quran-de/quran-de.sty
%{_tl_texmf}/tex/xelatex/quran-de/qurantext-deii.translation.def
%{_tl_texmf}/tex/xelatex/quran-de/qurantext-deiii.translation.def
%{_tl_texmf}/tex/xelatex/quran-de/qurantext-deiv.translation.def

%changelog
* Sat Sep 26 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260926-1
- rolled to tlnet snapshot 20260926 (22 members)
