# Generated by rust2rpm 28, adapted to this repo's conventions:
# spelled-out crates.io Source URL (mock fetches sources before buildroot
# macros exist), online cargo prep/license macros (anda-srpm-macros), tests
# disabled, explicit Release + changelog.
%undefine __brp_mangle_shebangs
%define debug_package %{nil}
# no debuginfo in the compiled objects either — nothing consumes it and it
# is a large share of compile time on big dependency trees
%define rustflags_debuginfo 0
%bcond check 0

%global crate eza

Name:           rust-eza
Version:        0.23.5
Release:        1%{?dist}
Summary:        Modern replacement for ls

License:        EUPL-1.2
URL:            https://crates.io/crates/eza
# the crates.io download URL spelled out: mock fetches sources at
# SRPM-build time, before the buildroot macros (anda-srpm-macros) exist
Source0:        https://static.crates.io/crates/%{crate}/%{crate}-%{version}.crate

BuildRequires:  anda-srpm-macros
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  mold
# compilation cache server — its cache dir lives on the workspace via the
# mock config's bind mount, shared across all rust source builds
BuildRequires:  sccache
BuildRequires:  cmake

%global _description %{expand:
A modern replacement for ls.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# aggregate of every linked crate's license, as carried by LICENSE.dependencies
License:        ((MIT OR Apache-2.0) AND Unicode-3.0) AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (MIT OR Apache-2.0 OR CC0-1.0) AND (MIT OR Apache-2.0) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT) AND EUPL-1.2 AND MIT AND MPL-2.0

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%license LICENSES/CC-BY-4.0.txt
%license LICENSES/EUPL-1.2.txt
%license LICENSES/MIT.txt
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc INSTALL.md
%doc README.md
%doc SECURITY.md
%doc TESTING.md
%{_bindir}/eza

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%license %{crate_instdir}/LICENSES/CC-BY-4.0.txt
%license %{crate_instdir}/LICENSES/EUPL-1.2.txt
%license %{crate_instdir}/LICENSES/MIT.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/INSTALL.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/SECURITY.md
%doc %{crate_instdir}/TESTING.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git-devel %{_description}

This package contains library source intended for building other packages which
use the "git" feature of the "%{crate}" crate.

%files       -n %{name}+git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git2-devel %{_description}

This package contains library source intended for building other packages which
use the "git2" feature of the "%{crate}" crate.

%files       -n %{name}+git2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nix-devel %{_description}

This package contains library source intended for building other packages which
use the "nix" feature of the "%{crate}" crate.

%files       -n %{name}+nix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nix-generated-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nix-generated-devel %{_description}

This package contains library source intended for building other packages which
use the "nix-generated" feature of the "%{crate}" crate.

%files       -n %{name}+nix-generated-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nix-local-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nix-local-devel %{_description}

This package contains library source intended for building other packages which
use the "nix-local" feature of the "%{crate}" crate.

%files       -n %{name}+nix-local-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+powertest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+powertest-devel %{_description}

This package contains library source intended for building other packages which
use the "powertest" feature of the "%{crate}" crate.

%files       -n %{name}+powertest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vendored-libgit2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vendored-libgit2-devel %{_description}

This package contains library source intended for building other packages which
use the "vendored-libgit2" feature of the "%{crate}" crate.

%files       -n %{name}+vendored-libgit2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vendored-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vendored-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "vendored-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+vendored-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep_online_sccache

%build
# cache dir on the workspace bind mount (see mock config) — survives across
# builds and is shared by every rust source build
export SCCACHE_DIR=/sccache
%{cargo_license_summary_online}
%{cargo_license_online} > LICENSE.dependencies

%install
export SCCACHE_DIR=/sccache
%cargo_install -- --locked

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Sep 25 2026 ahsan <aahsnr041@proton.me> - 0.23.5-1
- source build with the terra rust2rpm macro set (was: prebuilt-binary
  wrapper over the release binary)

