# GENERATED by tools/texlive-splitter from tlnet-archive snapshot 20260925 — do not
# edit by hand. Regenerated by the biweekly texlive roll (.github/workflows/
# texlive-update.yml -> tools/texlive-splitter/roll.py); never swept by the
# Monday update.yml. Arch-style group split of TeX Live scheme-full: the
# texmf-dist data tree only, no docs, no binaries (the image pairs
# Fedora's texlive engines with this tree).
# The build fetches this group's member tarballs from the immutable dated
# snapshot during %%build (network is on in Copr; the dated URL keeps
# builds reproducible). Inter-group Requires are version-pinned so dnf
# keeps all installed groups on one snapshot.
%define debug_package %{nil}
%global __brp_mangle_shebangs %{nil}
%global _unpackaged_files_terminate_build 0

Name:           texlive-langczechslovak
Version:        20260925
Release:        1%{?dist}
Summary:        TeX Live langczechslovak collection — Czech/Slovak
BuildArch:      noarch
License:        GPL-1.0-or-later AND BSD-3-Clause AND LPPL-1.3c AND MIT AND public-domain
URL:            https://tug.org/texlive/

%global _tl_archive_url https://texlive.info/tlnet-archive/2026/09/25/tlnet
%global _tl_texmf %{_datadir}/texlive/texmf-dist

BuildRequires:  tar
BuildRequires:  wget
BuildRequires:  xz
Requires:       texlive-basic = %{version}
Requires:       texlive-latex = %{version}

%description
TeX Live langczechslovak collection (Czech/Slovak) — the texmf-dist data tree
from tlnet snapshot 20260925, without documentation. Binaries come from
Fedora's texlive packaging; install texlive-meta for the whole scheme.

%build
mkdir -p raw
cat > members.txt <<'EOF'
babel-czech
babel-slovak
cnbwp
cs
csbulletin
cslatex
csplain
hyphen-czech
hyphen-slovak
EOF
xargs -a members.txt -P 8 -I PKG wget -q --retry-connrefused \
    --waitretry=5 --tries=5 -O raw/PKG.tar.xz \
    "%{_tl_archive_url}/archive/PKG.tar.xz"
for t in raw/*.tar.xz; do tar -xJf "$t" -C raw; done
# one merged tree. Member tarballs come in two shapes: relocatable ones
# unpack the texmf SUBDIRS at the root (tex/, fonts/, bibtex/, dvips/, ...
# — the tlpdb's RELOC notation on the wire: tex/ must land at
# texmf-dist/tex/, so the top-level dir names are preserved), while
# non-relocatable ones unpack texmf-dist/ already rooted plus their
# private tlpkg/ tlpdb copy. A mixed member's bin/ tree stays out of this
# noarch data split.
mkdir -p staging/texmf-dist
for entry in raw/*; do
    base="$(basename "$entry")"
    case "$base" in tlpkg|bin) continue ;; esac
    [ -d "$entry" ] || continue
    case "$base" in
        texmf-dist|RELOC) cp -a "$entry/." staging/texmf-dist/ ;;
        *)                cp -a "$entry"   staging/texmf-dist/ ;;
    esac
done
# the tarballs bundle documentation; none ships (no docfiles are claimed).
# texmf-dist/source/ STAYS: those files are runfiles in the tlpdb (koma-
# script's are claimed), and install-tl's option_src only governed the
# separate texmf-src tree — the old validated staging shipped them too.
rm -rf staging/texmf-dist/doc

%install
mkdir -p "%{buildroot}%{_tl_texmf}"
cp -a staging/texmf-dist/. "%{buildroot}%{_tl_texmf}/"

%files
%{_tl_texmf}/bibtex/bst/cnbwp/abbrvcnb.bst
%{_tl_texmf}/fonts/enc/dvips/cs/xl2.enc
%{_tl_texmf}/fonts/enc/dvips/cs/xl2f.enc
%{_tl_texmf}/fonts/enc/dvips/cs/xt2.enc
%{_tl_texmf}/fonts/map/dvips/cs/cs-a35-nodownload.map
%{_tl_texmf}/fonts/map/dvips/cs/cs-a35-urwdownload.map
%{_tl_texmf}/fonts/map/dvips/cs/cs-charter.map
%{_tl_texmf}/fonts/map/dvips/cs/csfonts.map
%{_tl_texmf}/fonts/source/public/cs/csaccent.mf
%{_tl_texmf}/fonts/source/public/cs/csacutl.mf
%{_tl_texmf}/fonts/source/public/cs/csacutu.mf
%{_tl_texmf}/fonts/source/public/cs/csadded.mf
%{_tl_texmf}/fonts/source/public/cs/csb10.mf
%{_tl_texmf}/fonts/source/public/cs/csb12.mf
%{_tl_texmf}/fonts/source/public/cs/csb17.mf
%{_tl_texmf}/fonts/source/public/cs/csb5.mf
%{_tl_texmf}/fonts/source/public/cs/csb6.mf
%{_tl_texmf}/fonts/source/public/cs/csb7.mf
%{_tl_texmf}/fonts/source/public/cs/csb8.mf
%{_tl_texmf}/fonts/source/public/cs/csb9.mf
%{_tl_texmf}/fonts/source/public/cs/csbx10.mf
%{_tl_texmf}/fonts/source/public/cs/csbx12.mf
%{_tl_texmf}/fonts/source/public/cs/csbx5.mf
%{_tl_texmf}/fonts/source/public/cs/csbx6.mf
%{_tl_texmf}/fonts/source/public/cs/csbx7.mf
%{_tl_texmf}/fonts/source/public/cs/csbx8.mf
%{_tl_texmf}/fonts/source/public/cs/csbx9.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl10.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl12.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl5.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl6.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl7.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl8.mf
%{_tl_texmf}/fonts/source/public/cs/csbxsl9.mf
%{_tl_texmf}/fonts/source/public/cs/csbxti10.mf
%{_tl_texmf}/fonts/source/public/cs/csbxti12.mf
%{_tl_texmf}/fonts/source/public/cs/csbxti17.mf
%{_tl_texmf}/fonts/source/public/cs/cscode.mf
%{_tl_texmf}/fonts/source/public/cs/cscsc10.mf
%{_tl_texmf}/fonts/source/public/cs/cscsc12.mf
%{_tl_texmf}/fonts/source/public/cs/cscsc17.mf
%{_tl_texmf}/fonts/source/public/cs/cscsc8.mf
%{_tl_texmf}/fonts/source/public/cs/cscsc9.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh10.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh12.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh17.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh5.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh6.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh7.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh8.mf
%{_tl_texmf}/fonts/source/public/cs/csdunh9.mf
%{_tl_texmf}/fonts/source/public/cs/csff10.mf
%{_tl_texmf}/fonts/source/public/cs/csfi10.mf
%{_tl_texmf}/fonts/source/public/cs/csfib10.mf
%{_tl_texmf}/fonts/source/public/cs/csfib12.mf
%{_tl_texmf}/fonts/source/public/cs/csfib8.mf
%{_tl_texmf}/fonts/source/public/cs/csfib9.mf
%{_tl_texmf}/fonts/source/public/cs/cshachel.mf
%{_tl_texmf}/fonts/source/public/cs/cshacheu.mf
%{_tl_texmf}/fonts/source/public/cs/cshyph.mf
%{_tl_texmf}/fonts/source/public/cs/csiacutl.mf
%{_tl_texmf}/fonts/source/public/cs/csihachl.mf
%{_tl_texmf}/fonts/source/public/cs/csinch.mf
%{_tl_texmf}/fonts/source/public/cs/csiothrl.mf
%{_tl_texmf}/fonts/source/public/cs/csitt10.mf
%{_tl_texmf}/fonts/source/public/cs/csitt12.mf
%{_tl_texmf}/fonts/source/public/cs/csitt17.mf
%{_tl_texmf}/fonts/source/public/cs/csitt8.mf
%{_tl_texmf}/fonts/source/public/cs/csitt9.mf
%{_tl_texmf}/fonts/source/public/cs/csotherl.mf
%{_tl_texmf}/fonts/source/public/cs/csotheru.mf
%{_tl_texmf}/fonts/source/public/cs/csr10.mf
%{_tl_texmf}/fonts/source/public/cs/csr12.mf
%{_tl_texmf}/fonts/source/public/cs/csr17.mf
%{_tl_texmf}/fonts/source/public/cs/csr5.mf
%{_tl_texmf}/fonts/source/public/cs/csr6.mf
%{_tl_texmf}/fonts/source/public/cs/csr7.mf
%{_tl_texmf}/fonts/source/public/cs/csr8.mf
%{_tl_texmf}/fonts/source/public/cs/csr9.mf
%{_tl_texmf}/fonts/source/public/cs/cssl10.mf
%{_tl_texmf}/fonts/source/public/cs/cssl12.mf
%{_tl_texmf}/fonts/source/public/cs/cssl17.mf
%{_tl_texmf}/fonts/source/public/cs/cssl5.mf
%{_tl_texmf}/fonts/source/public/cs/cssl6.mf
%{_tl_texmf}/fonts/source/public/cs/cssl7.mf
%{_tl_texmf}/fonts/source/public/cs/cssl8.mf
%{_tl_texmf}/fonts/source/public/cs/cssl9.mf
%{_tl_texmf}/fonts/source/public/cs/cssltt10.mf
%{_tl_texmf}/fonts/source/public/cs/cssltt12.mf
%{_tl_texmf}/fonts/source/public/cs/cssltt8.mf
%{_tl_texmf}/fonts/source/public/cs/cssltt9.mf
%{_tl_texmf}/fonts/source/public/cs/csss10.mf
%{_tl_texmf}/fonts/source/public/cs/csss12.mf
%{_tl_texmf}/fonts/source/public/cs/csss17.mf
%{_tl_texmf}/fonts/source/public/cs/csss8.mf
%{_tl_texmf}/fonts/source/public/cs/csss9.mf
%{_tl_texmf}/fonts/source/public/cs/csssbx10.mf
%{_tl_texmf}/fonts/source/public/cs/csssbx12.mf
%{_tl_texmf}/fonts/source/public/cs/csssbx17.mf
%{_tl_texmf}/fonts/source/public/cs/csssbx9.mf
%{_tl_texmf}/fonts/source/public/cs/csssdc10.mf
%{_tl_texmf}/fonts/source/public/cs/csssi10.mf
%{_tl_texmf}/fonts/source/public/cs/csssi12.mf
%{_tl_texmf}/fonts/source/public/cs/csssi17.mf
%{_tl_texmf}/fonts/source/public/cs/csssi8.mf
%{_tl_texmf}/fonts/source/public/cs/csssi9.mf
%{_tl_texmf}/fonts/source/public/cs/csssq8.mf
%{_tl_texmf}/fonts/source/public/cs/csssqi8.mf
%{_tl_texmf}/fonts/source/public/cs/cstcsc10.mf
%{_tl_texmf}/fonts/source/public/cs/cstcsc12.mf
%{_tl_texmf}/fonts/source/public/cs/cstcsc17.mf
%{_tl_texmf}/fonts/source/public/cs/cstex10.mf
%{_tl_texmf}/fonts/source/public/cs/cstex8.mf
%{_tl_texmf}/fonts/source/public/cs/cstex9.mf
%{_tl_texmf}/fonts/source/public/cs/csti10.mf
%{_tl_texmf}/fonts/source/public/cs/csti12.mf
%{_tl_texmf}/fonts/source/public/cs/csti17.mf
%{_tl_texmf}/fonts/source/public/cs/csti7.mf
%{_tl_texmf}/fonts/source/public/cs/csti8.mf
%{_tl_texmf}/fonts/source/public/cs/csti9.mf
%{_tl_texmf}/fonts/source/public/cs/cstt10.mf
%{_tl_texmf}/fonts/source/public/cs/cstt12.mf
%{_tl_texmf}/fonts/source/public/cs/cstt8.mf
%{_tl_texmf}/fonts/source/public/cs/cstt9.mf
%{_tl_texmf}/fonts/source/public/cs/csu10.mf
%{_tl_texmf}/fonts/source/public/cs/csu12.mf
%{_tl_texmf}/fonts/source/public/cs/csu17.mf
%{_tl_texmf}/fonts/source/public/cs/csu7.mf
%{_tl_texmf}/fonts/source/public/cs/csu8.mf
%{_tl_texmf}/fonts/source/public/cs/csu9.mf
%{_tl_texmf}/fonts/source/public/cs/csvtt10.mf
%{_tl_texmf}/fonts/source/public/cs/csvtt12.mf
%{_tl_texmf}/fonts/source/public/cs/csvtt8.mf
%{_tl_texmf}/fonts/source/public/cs/csvtt9.mf
%{_tl_texmf}/fonts/source/public/cs/icscsc10.mf
%{_tl_texmf}/fonts/source/public/cs/icstt8.mf
%{_tl_texmf}/fonts/source/public/cs/ilcsss8.mf
%{_tl_texmf}/fonts/source/public/cs/ilcsssb8.mf
%{_tl_texmf}/fonts/source/public/cs/ilcsssi8.mf
%{_tl_texmf}/fonts/source/public/cs/kmcsc.mf
%{_tl_texmf}/fonts/source/public/cs/kmroman.mf
%{_tl_texmf}/fonts/source/public/cs/kmtexset.mf
%{_tl_texmf}/fonts/source/public/cs/kmtextit.mf
%{_tl_texmf}/fonts/source/public/cs/kmtitle.mf
%{_tl_texmf}/fonts/source/public/cs/lcsss8.mf
%{_tl_texmf}/fonts/source/public/cs/lcsssb8.mf
%{_tl_texmf}/fonts/source/public/cs/lcsssi8.mf
%{_tl_texmf}/fonts/tfm/cs/cs-a35/README
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagd8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagdc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagdo8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagk8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagkc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pagko8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbkd8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbkdc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbkdi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbkl8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbklc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pbkli8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrb8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrbc8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrbo8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrr8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrrc8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pcrro8u.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvb8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvbc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvbn8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvbnc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvbo8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvbon8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvr8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvrc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvrn8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvrnc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvro8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/phvron8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncb8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncbc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncbi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncr8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncrc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pncri8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplb8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplbc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplbi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplr8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplrc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pplri8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmb8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmbc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmbi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmr8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmrc8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/ptmri8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-a35/pzcmi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/bchb8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/bchbi8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/bchr8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/bchri8z.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/rbchb.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/rbchbi.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/rbchr.tfm
%{_tl_texmf}/fonts/tfm/cs/cs-charter/rbchri.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csb9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbx9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxsl9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxti10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxti12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csbxti17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cscsc10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cscsc12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cscsc17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cscsc8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cscsc9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csdunh9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csff10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csfi10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csfib10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csfib12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csfib8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csfib9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csinch.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csitt10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csitt12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csitt17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csitt8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csitt9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csr9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl5.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl6.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssl9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssltt10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssltt12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssltt8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cssltt9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csss10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csss12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csss17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csss8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csss9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssbx10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssbx12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssbx17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssbx9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssdc10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssi10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssi12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssi17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssi8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssi9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssq8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csssqi8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstcsc10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstcsc12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstcsc17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csti9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstt10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstt12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstt8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/cstt9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu17.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu7.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csu9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csvtt10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csvtt12.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csvtt8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/csvtt9.tfm
%{_tl_texmf}/fonts/tfm/public/cs/icscsc10.tfm
%{_tl_texmf}/fonts/tfm/public/cs/icstt8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/ilcsss8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/ilcsssb8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/ilcsssi8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/lcsss8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/lcsssb8.tfm
%{_tl_texmf}/fonts/tfm/public/cs/lcsssi8.tfm
%{_tl_texmf}/fonts/type1/public/cs/README
%{_tl_texmf}/fonts/type1/public/cs/csb10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx12.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx5.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx6.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx7.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbx9.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbxsl10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csbxti10.pfb
%{_tl_texmf}/fonts/type1/public/cs/cscsc10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csdunh10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csff10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csfi10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csfib8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csinch.pfb
%{_tl_texmf}/fonts/type1/public/cs/csitt10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr12.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr17.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr5.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr6.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr7.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csr9.pfb
%{_tl_texmf}/fonts/type1/public/cs/cssl10.pfb
%{_tl_texmf}/fonts/type1/public/cs/cssl12.pfb
%{_tl_texmf}/fonts/type1/public/cs/cssl8.pfb
%{_tl_texmf}/fonts/type1/public/cs/cssl9.pfb
%{_tl_texmf}/fonts/type1/public/cs/cssltt10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csss10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csss12.pfb
%{_tl_texmf}/fonts/type1/public/cs/csss17.pfb
%{_tl_texmf}/fonts/type1/public/cs/csss8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csss9.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssbx10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssdc10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssi10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssi12.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssi17.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssi8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssi9.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssq8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csssqi8.pfb
%{_tl_texmf}/fonts/type1/public/cs/cstcsc10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csti10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csti12.pfb
%{_tl_texmf}/fonts/type1/public/cs/csti7.pfb
%{_tl_texmf}/fonts/type1/public/cs/csti8.pfb
%{_tl_texmf}/fonts/type1/public/cs/csti9.pfb
%{_tl_texmf}/fonts/type1/public/cs/cstt10.pfb
%{_tl_texmf}/fonts/type1/public/cs/cstt12.pfb
%{_tl_texmf}/fonts/type1/public/cs/cstt8.pfb
%{_tl_texmf}/fonts/type1/public/cs/cstt9.pfb
%{_tl_texmf}/fonts/type1/public/cs/csu10.pfb
%{_tl_texmf}/fonts/type1/public/cs/csvtt10.pfb
%{_tl_texmf}/fonts/vf/cs/cs-a35/README
%{_tl_texmf}/fonts/vf/cs/cs-a35/pagdc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pagkc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pbkdc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pbklc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pcrbc8u.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pcrrc8u.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/phvbc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/phvbnc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/phvrc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/phvrnc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pncbc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pncrc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pplbc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/pplrc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/ptmbc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-a35/ptmrc8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-charter/bchb8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-charter/bchbi8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-charter/bchr8z.vf
%{_tl_texmf}/fonts/vf/cs/cs-charter/bchri8z.vf
%{_tl_texmf}/makeindex/cnbwp/cnbindex.ist
%{_tl_texmf}/tex/cslatex/base/cslatex.ini
%{_tl_texmf}/tex/cslatex/base/czech.sty
%{_tl_texmf}/tex/cslatex/base/fonttext.cfg
%{_tl_texmf}/tex/cslatex/base/hyphen.cfg
%{_tl_texmf}/tex/cslatex/base/il2cmdh.fd
%{_tl_texmf}/tex/cslatex/base/il2cmfib.fd
%{_tl_texmf}/tex/cslatex/base/il2cmfr.fd
%{_tl_texmf}/tex/cslatex/base/il2cmr.fd
%{_tl_texmf}/tex/cslatex/base/il2cmss.fd
%{_tl_texmf}/tex/cslatex/base/il2cmtt.fd
%{_tl_texmf}/tex/cslatex/base/il2cmvtt.fd
%{_tl_texmf}/tex/cslatex/base/il2enc.def
%{_tl_texmf}/tex/cslatex/base/il2lcmss.fd
%{_tl_texmf}/tex/cslatex/base/il2lcmtt.fd
%{_tl_texmf}/tex/cslatex/base/slovak.sty
%{_tl_texmf}/tex/cslatex/cspsfonts/cspsfont.il2
%{_tl_texmf}/tex/cslatex/cspsfonts/cspsfont.tex
%{_tl_texmf}/tex/cslatex/cspsfonts/cspsfont.xl2
%{_tl_texmf}/tex/cslatex/cspsfonts/il2pag.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2pbk.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2pcr.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2phv.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2phvn.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2pnc.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2ppl.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2ptm.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/il2pzc.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/nhelvet.sty
%{_tl_texmf}/tex/cslatex/cspsfonts/ntimes.sty
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2pag.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2pbk.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2pcr.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2phv.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2phvn.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2pnc.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2ppl.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2ptm.fd
%{_tl_texmf}/tex/cslatex/cspsfonts/xl2pzc.fd
%{_tl_texmf}/tex/csplain/base/csenc-k.tex
%{_tl_texmf}/tex/csplain/base/csenc-p.tex
%{_tl_texmf}/tex/csplain/base/csenc-u.tex
%{_tl_texmf}/tex/csplain/base/csenc-w.tex
%{_tl_texmf}/tex/csplain/base/cseplain.ini
%{_tl_texmf}/tex/csplain/base/csfonts.tex
%{_tl_texmf}/tex/csplain/base/csfontsm.tex
%{_tl_texmf}/tex/csplain/base/csplain-utf8.ini
%{_tl_texmf}/tex/csplain/base/csplain.ini
%{_tl_texmf}/tex/csplain/base/czhyphen.ex
%{_tl_texmf}/tex/csplain/base/czhyphen.tex
%{_tl_texmf}/tex/csplain/base/etex-mac.tex
%{_tl_texmf}/tex/csplain/base/extcode.tex
%{_tl_texmf}/tex/csplain/base/fonttabs.tex
%{_tl_texmf}/tex/csplain/base/hyphen.ex
%{_tl_texmf}/tex/csplain/base/hyphen.lan
%{_tl_texmf}/tex/csplain/base/il2code.tex
%{_tl_texmf}/tex/csplain/base/lua-hyphen.lan
%{_tl_texmf}/tex/csplain/base/luaplain.ini
%{_tl_texmf}/tex/csplain/base/plaina4.tex
%{_tl_texmf}/tex/csplain/base/skhyphen.ex
%{_tl_texmf}/tex/csplain/base/skhyphen.tex
%{_tl_texmf}/tex/csplain/base/t1code.tex
%{_tl_texmf}/tex/csplain/base/t1enc-u.tex
%{_tl_texmf}/tex/csplain/base/ucode.tex
%{_tl_texmf}/tex/csplain/base/uni-lcuc.tex
%{_tl_texmf}/tex/csplain/base/xeplain.ini
%{_tl_texmf}/tex/csplain/fonts/ams-math.tex
%{_tl_texmf}/tex/csplain/fonts/cavantga.tex
%{_tl_texmf}/tex/csplain/fonts/cbookman.tex
%{_tl_texmf}/tex/csplain/fonts/chars-8z.tex
%{_tl_texmf}/tex/csplain/fonts/chelvet.tex
%{_tl_texmf}/tex/csplain/fonts/cncent.tex
%{_tl_texmf}/tex/csplain/fonts/cpalatin.tex
%{_tl_texmf}/tex/csplain/fonts/cs-adventor.tex
%{_tl_texmf}/tex/csplain/fonts/cs-all.tex
%{_tl_texmf}/tex/csplain/fonts/cs-antt.tex
%{_tl_texmf}/tex/csplain/fonts/cs-arev.tex
%{_tl_texmf}/tex/csplain/fonts/cs-baskerx.tex
%{_tl_texmf}/tex/csplain/fonts/cs-bera.tex
%{_tl_texmf}/tex/csplain/fonts/cs-bonum.tex
%{_tl_texmf}/tex/csplain/fonts/cs-charter.tex
%{_tl_texmf}/tex/csplain/fonts/cs-cursor.tex
%{_tl_texmf}/tex/csplain/fonts/cs-ebgaramond.tex
%{_tl_texmf}/tex/csplain/fonts/cs-heros.tex
%{_tl_texmf}/tex/csplain/fonts/cs-heuristica.tex
%{_tl_texmf}/tex/csplain/fonts/cs-iwona.tex
%{_tl_texmf}/tex/csplain/fonts/cs-kurier.tex
%{_tl_texmf}/tex/csplain/fonts/cs-libertine.tex
%{_tl_texmf}/tex/csplain/fonts/cs-pagella.tex
%{_tl_texmf}/tex/csplain/fonts/cs-polta.tex
%{_tl_texmf}/tex/csplain/fonts/cs-schola.tex
%{_tl_texmf}/tex/csplain/fonts/cs-termes.tex
%{_tl_texmf}/tex/csplain/fonts/ctimes.tex
%{_tl_texmf}/tex/csplain/fonts/cyrchars.tex
%{_tl_texmf}/tex/csplain/fonts/dcfonts.tex
%{_tl_texmf}/tex/csplain/fonts/ecfonts.tex
%{_tl_texmf}/tex/csplain/fonts/exchars.tex
%{_tl_texmf}/tex/csplain/fonts/ff-mac.tex
%{_tl_texmf}/tex/csplain/fonts/glyphtounicode-cs.tex
%{_tl_texmf}/tex/csplain/fonts/ki-math.tex
%{_tl_texmf}/tex/csplain/fonts/kp-fonts.tex
%{_tl_texmf}/tex/csplain/fonts/kp-math.tex
%{_tl_texmf}/tex/csplain/fonts/lmfonts.tex
%{_tl_texmf}/tex/csplain/fonts/luafonts.tex
%{_tl_texmf}/tex/csplain/fonts/ntx-math.tex
%{_tl_texmf}/tex/csplain/fonts/pazo-math.tex
%{_tl_texmf}/tex/csplain/fonts/tx-math.tex
%{_tl_texmf}/tex/csplain/fonts/uni-math.tex
%{_tl_texmf}/tex/csplain/fonts/unifam.tex
%{_tl_texmf}/tex/csplain/opmac/fontfam-catalog.tex
%{_tl_texmf}/tex/csplain/opmac/fontfam-global.tex
%{_tl_texmf}/tex/csplain/opmac/fontfam.tex
%{_tl_texmf}/tex/csplain/opmac/op-example.bib
%{_tl_texmf}/tex/csplain/opmac/opmac-bib-iso690.tex
%{_tl_texmf}/tex/csplain/opmac/opmac-bib-simple.tex
%{_tl_texmf}/tex/csplain/opmac/opmac-bib.tex
%{_tl_texmf}/tex/csplain/opmac/opmac-luatex.tex
%{_tl_texmf}/tex/csplain/opmac/opmac-xetex.tex
%{_tl_texmf}/tex/csplain/opmac/opmac.tex
%{_tl_texmf}/tex/csplain/opmac/pdfuni.tex
%{_tl_texmf}/tex/generic/babel-czech/czech.ldf
%{_tl_texmf}/tex/generic/babel-slovak/slovak.ldf
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-cs.tex
%{_tl_texmf}/tex/generic/hyph-utf8/loadhyph/loadhyph-sk.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-cs.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/ptex/hyph-sk.ec.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-cs.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/tex/hyph-sk.tex
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-cs.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-cs.pat.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-sk.hyp.txt
%{_tl_texmf}/tex/generic/hyph-utf8/patterns/txt/hyph-sk.pat.txt
%{_tl_texmf}/tex/latex/cnbwp/cnbwp-manual.sty
%{_tl_texmf}/tex/latex/cnbwp/cnbwp.cls
%{_tl_texmf}/tex/latex/cnbwp/cnbwpsizes.clo
%{_tl_texmf}/tex/latex/csbulletin/csbulacronym.sty
%{_tl_texmf}/tex/latex/csbulletin/csbulletin.cls
%{_tl_texmf}/tex/latex/csbulletin/csbulobalka.cls
%{_tl_texmf}/tex/latex/csbulletin/csbulobalka.sty
%{_tl_texmf}/tex/latex/csbulletin/csbulv1.cls

%changelog
* Fri Sep 25 2026 halcyon-autoupdate <aahsnr041@proton.me> - 20260925-1
- rolled to tlnet snapshot 20260925 (9 members)
